"""Cat breed reference data for the petcare-companion backend.

45 well-known cat breeds with care, temperament, and health reference data.
"""

SPECIES_NAME = "cat"

BREEDS = [
    {
        "name": "Maine Coon",
        "size_category": "large",
        "weight_range_min": 5.5,
        "weight_range_max": 11.0,
        "lifespan_years": "10-13",
        "coat_type": "Long, shaggy, water-resistant double coat",
        "shedding_level": "high",
        "grooming_freq": "Brush 2-3 times per week; daily during shedding season",
        "energy_level": "moderate",
        "trainability": "easy",
        "good_with_kids": "Excellent",
        "good_with_dogs": "Very good",
        "common_health_issues": "Hypertrophic cardiomyopathy (HCM), hip dysplasia, spinal muscular atrophy, polycystic kidney disease (PKD)",
        "exercise_needs_min": "30 minutes of interactive play daily",
        "care_notes": "Gentle giant; slow to mature (up to 4-5 years). Keep litter boxes extra large and provide climbing space. Watch weight.",
        "diet_sensitivities": "Prone to obesity; portion control recommended. No widespread specific allergies.",
        "origin": "Maine, United States",
        "temperament": "Gentle, friendly, sociable, dog-like, intelligent, easygoing.",
    },
    {
        "name": "Ragdoll",
        "size_category": "large",
        "weight_range_min": 4.5,
        "weight_range_max": 9.0,
        "lifespan_years": "12-15",
        "coat_type": "Semi-long, silky, low-matting single coat",
        "shedding_level": "moderate",
        "grooming_freq": "Brush twice weekly to prevent tangles",
        "energy_level": "low to moderate",
        "trainability": "easy",
        "good_with_kids": "Excellent",
        "good_with_dogs": "Very good",
        "common_health_issues": "Hypertrophic cardiomyopathy (HCM), bladder stones, obesity, Feline Mucopolysaccharidosis (rare)",
        "exercise_needs_min": "20-30 minutes of gentle play daily",
        "care_notes": "Docile lap cat; should be kept indoors due to trusting nature. Goes limp when picked up ('floppy' trait).",
        "diet_sensitivities": "Prone to obesity as adults; monitor portions. Some lines have sensitive stomachs.",
        "origin": "California, United States (1960s)",
        "temperament": "Docile, affectionate, calm, people-oriented, placid.",
    },
    {
        "name": "Siamese",
        "size_category": "medium",
        "weight_range_min": 2.5,
        "weight_range_max": 5.5,
        "lifespan_years": "12-20",
        "coat_type": "Short, fine, glossy coat with color points",
        "shedding_level": "low to moderate",
        "grooming_freq": "Weekly brushing",
        "energy_level": "high",
        "trainability": "easy",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good",
        "common_health_issues": "Progressive retinal atrophy, amyloidosis, asthma/bronchial disease, gastrointestinal issues, crossed eyes (historically), dental disease",
        "exercise_needs_min": "40-60 minutes of active play daily",
        "care_notes": "Extremely vocal and demanding of attention; does not do well left alone for long periods. Needs mental stimulation.",
        "diet_sensitivities": "Some prone to food sensitivities causing GI upset; avoid sudden diet changes.",
        "origin": "Thailand (Siam)",
        "temperament": "Vocal, social, intelligent, affectionate, curious, demanding.",
    },
    {
        "name": "Persian",
        "size_category": "medium",
        "weight_range_min": 3.0,
        "weight_range_max": 6.5,
        "lifespan_years": "10-17",
        "coat_type": "Long, thick, flowing double coat; flat (brachycephalic) face",
        "shedding_level": "high",
        "grooming_freq": "Daily brushing plus regular face cleaning; frequent bathing ideal",
        "energy_level": "low",
        "trainability": "moderate",
        "good_with_kids": "Good with gentle children",
        "good_with_dogs": "Good with calm dogs",
        "common_health_issues": "Polycystic kidney disease (PKD), hypertrophic cardiomyopathy (HCM), brachycephalic airway syndrome, tear duct overflow (epiphora), dental malocclusion",
        "exercise_needs_min": "15-20 minutes of light play daily",
        "care_notes": "High-maintenance grooming is essential or the coat mats badly. Flat face requires daily eye wiping. Indoor cat.",
        "diet_sensitivities": "Special flat-faced kibble shapes help eating; some have digestive sensitivities. Watch for calcium oxalate bladder stones.",
        "origin": "Iran (Persia)",
        "temperament": "Calm, quiet, sweet, dignified, undemanding.",
    },
    {
        "name": "British Shorthair",
        "size_category": "medium to large",
        "weight_range_min": 3.5,
        "weight_range_max": 7.5,
        "lifespan_years": "12-20",
        "coat_type": "Short, dense, plush double coat",
        "shedding_level": "moderate to high",
        "grooming_freq": "Brush once or twice weekly",
        "energy_level": "low to moderate",
        "trainability": "moderate",
        "good_with_kids": "Very good",
        "good_with_dogs": "Good",
        "common_health_issues": "Hypertrophic cardiomyopathy (HCM), polycystic kidney disease (PKD), obesity, hemophilia B",
        "exercise_needs_min": "20-30 minutes of play daily; encourage movement to prevent weight gain",
        "care_notes": "Sturdy and independent; affectionate but not a lap cat. Prone to weight gain — measure food carefully.",
        "diet_sensitivities": "Obesity-prone breed; calorie-controlled diet important. Some males develop urinary issues.",
        "origin": "United Kingdom",
        "temperament": "Easygoing, dignified, loyal, reserved, patient.",
    },
    {
        "name": "Bengal",
        "size_category": "medium to large",
        "weight_range_min": 3.5,
        "weight_range_max": 7.0,
        "lifespan_years": "12-16",
        "coat_type": "Short, sleek, uniquely marbled/spotted pelt-like coat",
        "shedding_level": "low to moderate",
        "grooming_freq": "Weekly brushing",
        "energy_level": "very high",
        "trainability": "easy",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good with well-socialized dogs",
        "common_health_issues": "Hypertrophic cardiomyopathy (HCM), progressive retinal atrophy, pyruvate kinase deficiency, patellar luxation, flat-chested kitten syndrome",
        "exercise_needs_min": "60+ minutes of vigorous play daily; needs climbing trees and puzzle toys",
        "care_notes": "Athletic and highly active — needs vertical space and enrichment. Fascinated by water. Not for first-time owners seeking a quiet pet.",
        "diet_sensitivities": "Often thrives on high-protein diets; some have sensitive stomachs and react poorly to grain-heavy foods.",
        "origin": "United States (Asian leopard cat hybrid)",
        "temperament": "Energetic, playful, confident, intelligent, vocal, adventurous.",
    },
    {
        "name": "Abyssinian",
        "size_category": "small to medium",
        "weight_range_min": 3.0,
        "weight_range_max": 5.0,
        "lifespan_years": "12-15",
        "coat_type": "Short, ticked (agouti) close-lying coat",
        "shedding_level": "low to moderate",
        "grooming_freq": "Weekly brushing",
        "energy_level": "very high",
        "trainability": "easy",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good",
        "common_health_issues": "Gingivitis/dental disease, pyruvate kinase deficiency, patellar luxation, progressive retinal atrophy, renal amyloidosis",
        "exercise_needs_min": "45-60 minutes of active play daily",
        "care_notes": "Perpetually in motion; needs lots of climbing space and interaction. Not a lap cat but very people-involved. Regular tooth brushing advised.",
        "diet_sensitivities": "No common specific allergies; high-quality protein diet supports high activity level.",
        "origin": "Southeast Asia / Ethiopia region (ancient lineage)",
        "temperament": "Active, playful, curious, intelligent, social.",
    },
    {
        "name": "Sphynx",
        "size_category": "medium",
        "weight_range_min": 3.0,
        "weight_range_max": 5.5,
        "lifespan_years": "9-15",
        "coat_type": "Hairless (fine peach-fuzz); warm to the touch",
        "shedding_level": "very low",
        "grooming_freq": "Weekly baths to remove skin oils; regular ear cleaning",
        "energy_level": "high",
        "trainability": "easy",
        "good_with_kids": "Excellent",
        "good_with_dogs": "Very good",
        "common_health_issues": "Hypertrophic cardiomyopathy (HCM), hereditary myopathy, skin conditions (urticaria pigmentosa), dental/gum disease, temperature sensitivity",
        "exercise_needs_min": "40 minutes of play daily",
        "care_notes": "Needs warmth: sweaters in cold weather and sun protection. Skin oils accumulate — weekly bathing required. Higher metabolism means bigger appetite.",
        "diet_sensitivities": "Higher caloric needs due to heat loss; feed energy-dense quality food. Some prone to GI sensitivity.",
        "origin": "Toronto, Canada (1966)",
        "temperament": "Affectionate, extroverted, energetic, mischievous, clingy.",
    },
    {
        "name": "Russian Blue",
        "size_category": "medium",
        "weight_range_min": 3.0,
        "weight_range_max": 5.5,
        "lifespan_years": "15-20",
        "coat_type": "Short, dense, plush double coat in blue-gray with silver tips",
        "shedding_level": "low to moderate",
        "grooming_freq": "Weekly brushing",
        "energy_level": "moderate",
        "trainability": "easy",
        "good_with_kids": "Good with respectful children",
        "good_with_dogs": "Good with calm dogs",
        "common_health_issues": "Generally healthy; bladder stones and obesity possible. Few breed-specific diseases.",
        "exercise_needs_min": "30 minutes of play daily",
        "care_notes": "Shy with strangers, deeply bonded with family. Likes routine; dislikes change. Keep indoors.",
        "diet_sensitivities": "Prone to obesity; may prefer scheduled meals over free feeding. Often has food preferences and can be picky.",
        "origin": "Arkhangelsk, Russia (Archangel Isles)",
        "temperament": "Quiet, gentle, reserved, loyal, intelligent.",
    },
    {
        "name": "Scottish Fold",
        "size_category": "medium",
        "weight_range_min": 3.0,
        "weight_range_max": 6.0,
        "lifespan_years": "11-15",
        "coat_type": "Short, dense coat (longhair variant exists) with folded ears",
        "shedding_level": "moderate",
        "grooming_freq": "Weekly brushing; check and clean folded ears regularly",
        "energy_level": "moderate",
        "trainability": "easy",
        "good_with_kids": "Excellent",
        "good_with_dogs": "Very good",
        "common_health_issues": "Osteochondrodysplasia (cartilage/bone abnormality linked to folded ears — all folds carry risk), polycystic kidney disease (PKD), HCM",
        "exercise_needs_min": "25-30 minutes of play daily",
        "care_notes": "The ear-fold gene causes cartilage problems; never breed two folds together. Watch for stiff, painful joints. Ethical sourcing is a concern.",
        "diet_sensitivities": "Joint-support diets (omega-3s, glucosamine) often beneficial; watch weight to reduce joint stress.",
        "origin": "Scotland (1961)",
        "temperament": "Sweet-tempered, calm, adaptable, affectionate, soft-spoken.",
    },
    {
        "name": "Birman",
        "size_category": "medium to large",
        "weight_range_min": 3.5,
        "weight_range_max": 6.5,
        "lifespan_years": "12-16",
        "coat_type": "Semi-long, silky single coat with color points and white gloves",
        "shedding_level": "moderate",
        "grooming_freq": "Brush twice weekly (single coat rarely mats)",
        "energy_level": "moderate",
        "trainability": "easy",
        "good_with_kids": "Excellent",
        "good_with_dogs": "Very good",
        "common_health_issues": "Hypertrophic cardiomyopathy (HCM), corneal dystrophy, spongiform degeneration (rare), obesity in later life",
        "exercise_needs_min": "25-30 minutes of play daily",
        "care_notes": "Gentle and adaptable companion; low-maintenance coat despite length. Keep indoors.",
        "diet_sensitivities": "Watch weight after age 5; otherwise no widespread sensitivities.",
        "origin": "Burma (Myanmar), developed in France",
        "temperament": "Gentle, affectionate, quiet, people-oriented, curious.",
    },
    {
        "name": "American Shorthair",
        "size_category": "medium to large",
        "weight_range_min": 3.5,
        "weight_range_max": 7.0,
        "lifespan_years": "15-20",
        "coat_type": "Short, dense, hard-textured coat in many colors/patterns",
        "shedding_level": "moderate to high",
        "grooming_freq": "Weekly brushing; more often during seasonal shedding",
        "energy_level": "moderate",
        "trainability": "easy",
        "good_with_kids": "Excellent",
        "good_with_dogs": "Excellent",
        "common_health_issues": "Hypertrophic cardiomyopathy (HCM), obesity, polycystic kidney disease (rare), dental disease",
        "exercise_needs_min": "30 minutes of play daily",
        "care_notes": "Hardy, easygoing working-cat heritage. Adaptable to most homes. Watch food intake — gains weight easily.",
        "diet_sensitivities": "Prone to obesity; measured portions advised. Otherwise robust digestively.",
        "origin": "United States (from European settlers' cats)",
        "temperament": "Adaptable, easygoing, friendly, independent yet sociable.",
    },
    {
        "name": "Devon Rex",
        "size_category": "small",
        "weight_range_min": 2.5,
        "weight_range_max": 4.5,
        "lifespan_years": "9-15",
        "coat_type": "Short, soft, wavy rex coat (sparse guard hairs)",
        "shedding_level": "low",
        "grooming_freq": "Minimal brushing (damages coat); occasional wipe-down, ear cleaning",
        "energy_level": "very high",
        "trainability": "easy",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good",
        "common_health_issues": "Hereditary myopathy, hypotrichosis, patellar luxation, HCM (some lines), ear wax buildup",
        "exercise_needs_min": "40+ minutes of play daily",
        "care_notes": "Heat-seeking 'pixie' cat; loves perching on shoulders and laps. Thin coat means it seeks warmth. Big appetite relative to size.",
        "diet_sensitivities": "High metabolism — needs calorie-dense diet. Generally not fussy.",
        "origin": "Devon, England (1959)",
        "temperament": "Playful, mischievous, affectionate, clownish, people-loving.",
    },
    {
        "name": "Norwegian Forest Cat",
        "size_category": "large",
        "weight_range_min": 4.0,
        "weight_range_max": 8.0,
        "lifespan_years": "12-16",
        "coat_type": "Long, glossy, water-resistant double coat with woolly undercoat",
        "shedding_level": "high",
        "grooming_freq": "Brush 2-3 times weekly; daily during spring shedding",
        "energy_level": "moderate",
        "trainability": "moderate",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good",
        "common_health_issues": "Hypertrophic cardiomyopathy (HCM), glycogen storage disease IV, hip dysplasia, polycystic kidney disease (PKD)",
        "exercise_needs_min": "30-40 minutes of play daily; loves climbing",
        "care_notes": "Expert climber — needs tall cat trees. Coat is surprisingly low-maintenance if brushed regularly. Slow to mature (~5 years).",
        "diet_sensitivities": "No widespread sensitivities; watch weight as an adult. Taurine-rich quality diet supports long coat health.",
        "origin": "Norway",
        "temperament": "Gentle, independent, intelligent, calm, adventurous.",
    },
    {
        "name": "Oriental Shorthair",
        "size_category": "small to medium",
        "weight_range_min": 2.5,
        "weight_range_max": 5.0,
        "lifespan_years": "12-15",
        "coat_type": "Short, sleek, close-lying coat in 300+ colors/patterns",
        "shedding_level": "low",
        "grooming_freq": "Weekly brushing",
        "energy_level": "very high",
        "trainability": "easy",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good",
        "common_health_issues": "Progressive retinal atrophy, amyloidosis, dilated cardiomyopathy, dental disease, respiratory issues (upper)",
        "exercise_needs_min": "50-60 minutes of active play daily",
        "care_notes": "Extremely attached and vocal — separation anxiety risk if left alone frequently. Best in pairs or busy households.",
        "diet_sensitivities": "Lean body type; no common allergies. Feed quality protein to sustain activity.",
        "origin": "England (Siamese-derived), United States",
        "temperament": "Vocal, curious, social, intelligent, energetic, devoted.",
    },
    {
        "name": "Tonkinese",
        "size_category": "medium",
        "weight_range_min": 2.7,
        "weight_range_max": 5.5,
        "lifespan_years": "12-16",
        "coat_type": "Short, silky, mink-patterned coat (between Siamese and Burmese coloring)",
        "shedding_level": "low",
        "grooming_freq": "Weekly brushing",
        "energy_level": "high",
        "trainability": "easy",
        "good_with_kids": "Excellent",
        "good_with_dogs": "Excellent",
        "common_health_issues": "Generally healthy; gingivitis, upper respiratory sensitivity in kittens, intestinal issues possible",
        "exercise_needs_min": "40 minutes of play daily",
        "care_notes": "People-first breed; dislikes being alone. Loves heights and games of fetch. Very social — consider two.",
        "diet_sensitivities": "No widespread specific sensitivities; maintain balanced diet to keep lean muscle.",
        "origin": "Canada / United States (1960s)",
        "temperament": "Outgoing, affectionate, playful, vocal, social.",
    },
    {
        "name": "Burmese",
        "size_category": "medium",
        "weight_range_min": 3.0,
        "weight_range_max": 6.0,
        "lifespan_years": "10-17 (often into late teens)",
        "coat_type": "Short, satin-like, close-lying coat",
        "shedding_level": "low",
        "grooming_freq": "Weekly polishing with a soft cloth or rubber brush",
        "energy_level": "high",
        "trainability": "easy",
        "good_with_kids": "Excellent",
        "good_with_dogs": "Very good",
        "common_health_issues": "Hypokaleemic polymyopathy (muscle weakness, in European lines), hypothyroidism, diabetes mellitus (in Australian/British lines), cranial deformities in kittens (rare), gingivitis",
        "exercise_needs_min": "35-45 minutes of play daily",
        "care_notes": "Dog-like follower that hates solitude. Surprisingly heavy for its size ('brick wrapped in silk'). Keep indoors.",
        "diet_sensitivities": "Diabetes predisposition in some lines — avoid free-feeding carbs; measured meals preferred.",
        "origin": "Burma (Myanmar), developed in the United States and United Kingdom",
        "temperament": "Affectionate, playful, bold, social, vocal.",
    },
    {
        "name": "Siberian",
        "size_category": "medium to large",
        "weight_range_min": 4.0,
        "weight_range_max": 8.0,
        "lifespan_years": "12-18",
        "coat_type": "Long, triple-coated, water-resistant fur",
        "shedding_level": "high",
        "grooming_freq": "Brush 2 times weekly; daily during heavy seasonal sheds",
        "energy_level": "moderate to high",
        "trainability": "easy",
        "good_with_kids": "Excellent",
        "good_with_dogs": "Excellent",
        "common_health_issues": "Hypertrophic cardiomyopathy (HCM), pyruvate kinase deficiency; generally robust overall",
        "exercise_needs_min": "30-45 minutes of play daily",
        "care_notes": "National cat of Russia; agile jumper with fascination for water. Lower Fel d 1 allergen levels than many breeds (not hypoallergenic). Slow to mature (~5 years).",
        "diet_sensitivities": "No widespread specific allergies; hearty appetite — watch portions to prevent weight gain.",
        "origin": "Russia (Siberia)",
        "temperament": "Friendly, playful, fearless, affectionate, dog-like.",
    },
    {
        "name": "Ragamuffin",
        "size_category": "large",
        "weight_range_min": 4.5,
        "weight_range_max": 9.0,
        "lifespan_years": "12-16",
        "coat_type": "Medium-long, plush, rabbit-like coat",
        "shedding_level": "moderate",
        "grooming_freq": "Brush twice weekly",
        "energy_level": "low to moderate",
        "trainability": "easy",
        "good_with_kids": "Excellent",
        "good_with_dogs": "Excellent",
        "common_health_issues": "Hypertrophic cardiomyopathy (HCM), polycystic kidney disease (PKD); generally healthy overall",
        "exercise_needs_min": "20-30 minutes of gentle play daily",
        "care_notes": "Big, docile teddy bear; matures slowly (about 4 years). Handles being carried well. Keep indoors.",
        "diet_sensitivities": "Obesity-prone; portion control important. No other common sensitivities.",
        "origin": "United States (derived from Ragdoll/stray street cats)",
        "temperament": "Docile, cuddly, friendly, calm, adaptable.",
    },
    {
        "name": "Exotic Shorthair",
        "size_category": "medium",
        "weight_range_min": 3.0,
        "weight_range_max": 6.5,
        "lifespan_years": "12-15",
        "coat_type": "Short, dense, plush double coat; brachycephalic (flat) face",
        "shedding_level": "moderate to high",
        "grooming_freq": "Brush 2 times weekly; daily eye wiping for flat face",
        "energy_level": "low to moderate",
        "trainability": "easy",
        "good_with_kids": "Very good with gentle children",
        "good_with_dogs": "Good with calm dogs",
        "common_health_issues": "Polycystic kidney disease (PKD), brachycephalic airway/breathing issues, tear duct overflow (epiphora), dental problems, HCM",
        "exercise_needs_min": "15-20 minutes of light play daily",
        "care_notes": "'Lazy man's Persian' — Persian temperament with easier coat. Needs facial fold cleaning. Sensitive to heat. Indoor only.",
        "diet_sensitivities": "Flat-faced cats may need shallow bowls/special kibble. Watch urinary health and weight.",
        "origin": "United States (Persian x American Shorthair cross)",
        "temperament": "Sweet, calm, quiet, affectionate, playful in short bursts.",
    },
    {
        "name": "Himalayan",
        "size_category": "medium",
        "weight_range_min": 3.0,
        "weight_range_max": 6.5,
        "lifespan_years": "9-15",
        "coat_type": "Long, thick Persian-type coat with Siamese-style color points",
        "shedding_level": "high",
        "grooming_freq": "Daily brushing; daily face/eye cleaning",
        "energy_level": "low",
        "trainability": "moderate",
        "good_with_kids": "Good with calm households",
        "good_with_dogs": "Good with calm dogs",
        "common_health_issues": "Polycystic kidney disease (PKD), brachycephalic breathing issues, eye tearing, HCM, dental malocclusion, ringworm susceptibility",
        "exercise_needs_min": "15-20 minutes of gentle play daily",
        "care_notes": "Highest-maintenance grooming of any breed — daily commitment required. Heat-sensitive; indoor only. Two varieties: extreme-faced and traditional.",
        "diet_sensitivities": "Same flat-face eating considerations as Persians; monitor for urinary stones and obesity.",
        "origin": "United States (Persian x Siamese cross, 1930s-1950s)",
        "temperament": "Gentle, calm, quiet, affectionate, dependent on people.",
    },
    {
        "name": "Savannah",
        "size_category": "medium to large (F1 generation larger)",
        "weight_range_min": 3.5,
        "weight_range_max": 9.0,
        "lifespan_years": "12-20",
        "coat_type": "Short, spotted, pelt-like coat",
        "shedding_level": "low",
        "grooming_freq": "Weekly brushing",
        "energy_level": "very high",
        "trainability": "easy (can learn leash walking, fetch, doors)",
        "good_with_kids": "Good with older, respectful kids",
        "good_with_dogs": "Good with dogs when raised together",
        "common_health_issues": "Generally healthy; potential for HCM, patellar luxation; early-generation hybrids need vet experienced with hybrids",
        "exercise_needs_min": "60+ minutes of vigorous activity daily; needs tall climbing structures",
        "care_notes": "Servial hybrid — legality varies by state/country and generation (F1-F5). Extremely athletic, can jump 2.5 m vertically. Needs secure home, escape-proof screens, and lots of enrichment.",
        "diet_sensitivities": "Early generations do better on high-protein, grain-free raw/premium diets; later generations adapt to standard premium food.",
        "origin": "United States (serval x domestic cat hybrid, 1986)",
        "temperament": "Confident, adventurous, energetic, curious, loyal.",
    },
    {
        "name": "Turkish Angora",
        "size_category": "small to medium",
        "weight_range_min": 2.5,
        "weight_range_max": 5.0,
        "lifespan_years": "12-18",
        "coat_type": "Long, silky, single coat (no undercoat)",
        "shedding_level": "moderate",
        "grooming_freq": "Brush twice weekly (single coat resists matting)",
        "energy_level": "high",
        "trainability": "easy",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good",
        "common_health_issues": "Deafness (linked to blue eyes/white coat, especially odd-eyed whites), ataxia (hereditary, in older lines), HCM",
        "exercise_needs_min": "35-45 minutes of play daily",
        "care_notes": "Graceful athlete that loves heights and water play. Test hearing in white/blue-eyed individuals. Elegant but mischievous.",
        "diet_sensitivities": "No widespread sensitivities; balanced premium diet suffices.",
        "origin": "Turkey (Ankara)",
        "temperament": "Intelligent, playful, affectionate, determined, social.",
    },
    {
        "name": "Bombay",
        "size_category": "small to medium",
        "weight_range_min": 2.7,
        "weight_range_max": 5.5,
        "lifespan_years": "12-18",
        "coat_type": "Short, tight, jet-black patent-leather coat with copper/gold eyes",
        "shedding_level": "low",
        "grooming_freq": "Weekly polish with rubber brush or hand-grooming",
        "energy_level": "moderate to high",
        "trainability": "easy (learns fetch and leash walking)",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good",
        "common_health_issues": "Hypertrophic cardiomyopathy (HCM), craniofacial defects (Burmesederived line issue), excessive tear secretion, anemia risk (Burmese-linked)",
        "exercise_needs_min": "30-40 minutes of play daily",
        "care_notes": "'Mini panther' lap cat bred from Burmese lines. Thrives on constant companionship; not suited to long absences. Indoor only.",
        "diet_sensitivities": "No common specific allergies; watch weight gain in adulthood.",
        "origin": "Kentucky, United States (1958)",
        "temperament": "Affectionate, outgoing, clever, social, attention-seeking.",
    },
    {
        "name": "Cornish Rex",
        "size_category": "small",
        "weight_range_min": 2.5,
        "weight_range_max": 4.5,
        "lifespan_years": "11-16",
        "coat_type": "Very short, soft, wavy rex coat (only down hairs — no guard hairs)",
        "shedding_level": "low",
        "grooming_freq": "Minimal brushing; occasional baths, ear cleaning",
        "energy_level": "very high",
        "trainability": "easy",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good",
        "common_health_issues": "Hypertrophic cardiomyopathy (HCM), patellar luxation, vitamin K-deficiency response (hereditary in some lines), sunburn risk on thin coat",
        "exercise_needs_min": "40-60 minutes of active play daily",
        "care_notes": "Greyhound of cats — hot-bodied, acrobatic, always playing. Seeks warmth (laps, heaters). Protect from cold drafts and direct sun.",
        "diet_sensitivities": "Fast metabolism — needs generous amounts of quality calories; usually not picky.",
        "origin": "Cornwall, England (1950)",
        "temperament": "Playful, mischievous, affectionate, energetic, acrobatic.",
    },
    {
        "name": "Manx",
        "size_category": "medium",
        "weight_range_min": 3.5,
        "weight_range_max": 5.5,
        "lifespan_years": "12-16",
        "coat_type": "Short double coat (longhair Cymric variant exists); tailless to full-tailed",
        "shedding_level": "moderate to high",
        "grooming_freq": "Brush twice weekly",
        "energy_level": "moderate",
        "trainability": "easy",
        "good_with_kids": "Excellent",
        "good_with_dogs": "Very good",
        "common_health_issues": "Manx syndrome (spina bifida/fused vertebrae from taillessness gene), arthritis of tail spine, corneal dystrophy, megacolon",
        "exercise_needs_min": "30 minutes of play daily",
        "care_notes": "Taillessness comes from a genetic mutation that can cause spinal defects — rumpies/rumpy-risers need monitoring. Rounded hop-like gait; loves water and fetching.",
        "diet_sensitivities": "Megacolon risk means high-fiber diet and hydration matter. Otherwise no widespread sensitivities.",
        "origin": "Isle of Man",
        "temperament": "Even-tempered, playful, loyal, intelligent, quiet.",
    },
    {
        "name": "British Longhair",
        "size_category": "medium to large",
        "weight_range_min": 3.5,
        "weight_range_max": 7.5,
        "lifespan_years": "12-18",
        "coat_type": "Long, dense, plush double coat",
        "shedding_level": "high",
        "grooming_freq": "Brush 2-3 times weekly; daily in shedding season",
        "energy_level": "low to moderate",
        "trainability": "moderate",
        "good_with_kids": "Very good",
        "good_with_dogs": "Good",
        "common_health_issues": "Polycystic kidney disease (PKD), HCM, obesity, diabetes risk with weight gain",
        "exercise_needs_min": "20-30 minutes of play daily",
        "care_notes": "Chill companion combining British Shorthair build with longer coat. Undemanding but enjoys company. Strict weight management needed.",
        "diet_sensitivities": "Obesity-prone; measured meals and hairball-control formulas helpful.",
        "origin": "United Kingdom",
        "temperament": "Calm, patient, affectionate, independent, easygoing.",
    },
    {
        "name": "Chartreux",
        "size_category": "medium to large",
        "weight_range_min": 3.0,
        "weight_range_max": 7.0,
        "lifespan_years": "12-15",
        "coat_type": "Short to medium, dense, water-repellent blue-gray double coat",
        "shedding_level": "moderate to high",
        "grooming_freq": "Weekly to twice-weekly brushing",
        "energy_level": "moderate",
        "trainability": "easy",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good",
        "common_health_issues": "Patellar luxation, hip dysplasia, polycystic kidney disease (rare), HCM (low incidence), dental/gum disease",
        "exercise_needs_min": "30 minutes of play daily",
        "care_notes": "Quiet French breed (famous for silence/smiling expression). Strong hunter instinct. Slow-growing — reaches maturity at 4-5 years.",
        "diet_sensitivities": "No widespread specific sensitivities; watch weight. Dental care recommended.",
        "origin": "France (Carthusian monasteries, legend-based)",
        "temperament": "Gentle, quiet, observant, affectionate, playful.",
    },
    {
        "name": "Somali",
        "size_category": "medium",
        "weight_range_min": 3.0,
        "weight_range_max": 5.5,
        "lifespan_years": "12-16",
        "coat_type": "Long, fluffy, ticked (agouti) fox-like coat",
        "shedding_level": "moderate to high",
        "grooming_freq": "Brush 2-3 times weekly",
        "energy_level": "very high",
        "trainability": "easy",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good",
        "common_health_issues": "Pyruvate kinase deficiency, progressive retinal atrophy, patellar luxation, gingivitis, renal amyloidosis (rare)",
        "exercise_needs_min": "45-60 minutes of active play daily",
        "care_notes": "Longhaired Abyssinian — busy, nosy, opens cabinets and plays with water. Needs lots of vertical space. Regular dental care essential.",
        "diet_sensitivities": "No widespread sensitivities; high-quality protein suits its activity level.",
        "origin": "England / North America (Abyssinian longhair mutation)",
        "temperament": "Playful, curious, energetic, mischievous, sociable.",
    },
    {
        "name": "Balinese",
        "size_category": "small to medium",
        "weight_range_min": 2.5,
        "weight_range_max": 5.0,
        "lifespan_years": "12-20",
        "coat_type": "Long, silky single coat with color points and plumed tail",
        "shedding_level": "low to moderate",
        "grooming_freq": "Brush once or twice weekly (single coat rarely mats)",
        "energy_level": "high",
        "trainability": "easy",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good",
        "common_health_issues": "Progressive retinal atrophy, amyloidosis, crossed eyes (occasional), dental/respiratory sensitivities like Siamese",
        "exercise_needs_min": "40-50 minutes of active play daily",
        "care_notes": "Longhaired Siamese — talkative and people-focused. Produces less Fel d 1 than many breeds (not truly hypoallergenic). Needs company and stimulation.",
        "diet_sensitivities": "Some lines show food/GI sensitivities similar to Siamese; introduce new foods gradually.",
        "origin": "United States (natural Siamese mutation)",
        "temperament": "Vocal, affectionate, intelligent, playful, social.",
    },
    {
        "name": "Japanese Bobtail",
        "size_category": "small to medium",
        "weight_range_min": 2.5,
        "weight_range_max": 5.0,
        "lifespan_years": "12-18",
        "coat_type": "Short (or longhair variety) with pom-pom bobbed tail",
        "shedding_level": "moderate",
        "grooming_freq": "Weekly brushing",
        "energy_level": "high",
        "trainability": "easy",
        "good_with_kids": "Excellent",
        "good_with_dogs": "Very good",
        "common_health_issues": "Generally healthy and hardy; bobbed tail is not associated with spinal problems unlike Manx. Occasional hip dysplasia and patellar issues.",
        "exercise_needs_min": "35-45 minutes of play daily",
        "care_notes": "Lucky-cat (maneki-neko) breed of Japan. Each bobtail is unique in structure. Very chatty with wide vocal range; loves fetch.",
        "diet_sensitivities": "No widespread sensitivities; standard premium diet adequate.",
        "origin": "Japan (centuries-old landrace)",
        "temperament": "Talkative, playful, affectionate, active, people-oriented.",
    },
    {
        "name": "Korat",
        "size_category": "small",
        "weight_range_min": 2.5,
        "weight_range_max": 4.5,
        "lifespan_years": "12-16",
        "coat_type": "Short, single, silver-tipped blue coat; heart-shaped face",
        "shedding_level": "low",
        "grooming_freq": "Weekly brushing",
        "energy_level": "moderate to high",
        "trainability": "easy",
        "good_with_kids": "Good with gentle children",
        "good_with_dogs": "Good",
        "common_health_issues": "GM1 gangliosidosis (storage disease — DNA test available), low body fat sensitivity to anesthesia; otherwise robust",
        "exercise_needs_min": "30-40 minutes of play daily",
        "care_notes": "Ancient Thai 'good luck' breed, traditionally given in pairs. Forms intense bonds; prefers familiar routine. Startle-sensitive to loud noises.",
        "diet_sensitivities": "Low body fat means it feels cold easily and cannot miss meals; consistent feeding schedule recommended.",
        "origin": "Thailand (Korat plateau)",
        "temperament": "Intelligent, possessive, gentle, alert, strongly bonded.",
    },
    {
        "name": "Singapura",
        "size_category": "small (smallest pedigree breed)",
        "weight_range_min": 1.8,
        "weight_range_max": 3.5,
        "lifespan_years": "12-17",
        "coat_type": "Short, fine, ivory coat with sepia agouti ticking",
        "shedding_level": "low",
        "grooming_freq": "Weekly brushing",
        "energy_level": "high",
        "trainability": "easy",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good",
        "common_health_issues": "Pyruvate kinase deficiency, uterine inertia in queens (cesarean risk); generally healthy otherwise",
        "exercise_needs_min": "35-45 minutes of play daily",
        "care_notes": "Tiny 'pesky people cat' that stays kitten-sized. Curious about everything including stovetops — kitten-proofing matters lifelong. Dislikes loud environments.",
        "diet_sensitivities": "Small stomachs do best with several small meals; no widespread allergies.",
        "origin": "Singapore (disputed; developed in the United States, 1970s)",
        "temperament": "Curious, affectionate, lively, mischievous, extroverted.",
    },
    {
        "name": "LaPerm",
        "size_category": "small to medium",
        "weight_range_min": 2.5,
        "weight_range_max": 4.5,
        "lifespan_years": "10-15",
        "coat_type": "Curly/wavy rex-type coat (short or long, sparse undercoat)",
        "shedding_level": "low to moderate",
        "grooming_freq": "Light weekly brushing (over-brushing ruins curls)",
        "energy_level": "moderate to high",
        "trainability": "easy",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good",
        "common_health_issues": "No known widespread breed-specific diseases; considered generally healthy",
        "exercise_needs_min": "30 minutes of play daily",
        "care_notes": "Farm-born Oregon mutation breed. Coat varies through life (kittens can go bald then re-curl). Touch-sensitive curls make them crave petting.",
        "diet_sensitivities": "None documented widely; standard premium diet appropriate.",
        "origin": "Oregon, United States (1982 barn-cat mutation)",
        "temperament": "Gentle, affectionate, curious, people-oriented, playful.",
    },
    {
        "name": "Munchkin",
        "size_category": "small to medium",
        "weight_range_min": 2.0,
        "weight_range_max": 4.5,
        "lifespan_years": "12-15",
        "coat_type": "Short or semi-long plush coat; characteristically short legs",
        "shedding_level": "moderate",
        "grooming_freq": "Weekly brushing (more for longhair variety)",
        "energy_level": "high",
        "trainability": "easy",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good",
        "common_health_issues": "Lordosis (spinal curvature), pectus excavatum (sunken chest) — both linked to the dwarfism gene; osteoarthritis risk later in life",
        "exercise_needs_min": "30 minutes of play daily (adapted ramps/steps for furniture)",
        "care_notes": "Short-legged but fast and playful; can't jump as high so provide steps and ramps. Controversial breeding due to skeletal gene — choose ethical breeders screening for lordosis.",
        "diet_sensitivities": "Weight control critical — extra weight stresses spine and joints.",
        "origin": "Louisiana, United States (1983 natural mutation)",
        "temperament": "Confident, outgoing, playful, friendly, curious.",
    },
    {
        "name": "Nebelung",
        "size_category": "medium",
        "weight_range_min": 3.0,
        "weight_range_max": 5.5,
        "lifespan_years": "11-18",
        "coat_type": "Long, dense, silky blue-gray double coat (Russian Blue type, longhair)",
        "shedding_level": "moderate to high",
        "grooming_freq": "Brush twice weekly; more in shedding season",
        "energy_level": "moderate",
        "trainability": "easy",
        "good_with_kids": "Good with calm children",
        "good_with_dogs": "Good with calm, respectful dogs",
        "common_health_issues": "Generally healthy; few known breed-specific issues. Bladder stones reported occasionally.",
        "exercise_needs_min": "25-30 minutes of play daily",
        "care_notes": "Rare 'creature of the mist.' Shy with strangers, devoted to chosen humans; thrives on predictable routine and quiet homes. Indoor only.",
        "diet_sensitivities": "Can be picky eaters; prefer consistency. Watch for weight gain in middle age.",
        "origin": "United States (1980s, Russian Blue longhair line)",
        "temperament": "Gentle, shy, devoted, intelligent, quiet.",
    },
    {
        "name": "Ocicat",
        "size_category": "medium",
        "weight_range_min": 3.0,
        "weight_range_max": 6.5,
        "lifespan_years": "12-18",
        "coat_type": "Short, sleek, satiny coat with spotted tabby pattern",
        "shedding_level": "low",
        "grooming_freq": "Weekly brushing or chamois polish",
        "energy_level": "very high",
        "trainability": "easy (learns tricks, leash, fetch)",
        "good_with_kids": "Excellent",
        "good_with_dogs": "Excellent",
        "common_health_issues": "Hypertrophic cardiomyopathy (HCM), hepatic amyloidosis, pyruvate kinase deficiency, periodontal disease",
        "exercise_needs_min": "45-60 minutes of vigorous play daily",
        "care_notes": "Wild-looking but fully domestic (no wild blood — Abyssinian/Siamese/American Shorthair mix). Dog-like: leash trains, greets guests, hates being alone. Provide climbing towers.",
        "diet_sensitivities": "No widespread sensitivities; lean muscular build benefits from high-quality protein.",
        "origin": "Michigan, United States (1964, accidental hybrid)",
        "temperament": "Active, sociable, confident, playful, devoted.",
    },
    {
        "name": "Pixiebob",
        "size_category": "medium to large",
        "weight_range_min": 3.5,
        "weight_range_max": 8.0,
        "lifespan_years": "13-16",
        "coat_type": "Short or long brown-spotted tabby coat; often bobbed tail and polydactyl feet",
        "shedding_level": "moderate to high",
        "grooming_freq": "Weekly to twice-weekly brushing",
        "energy_level": "moderate",
        "trainability": "easy (leash training, fetch)",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good",
        "common_health_issues": "Generally healthy; cryptorchidism occurs in some lines, dystocia in queens; no widespread serious disorders",
        "exercise_needs_min": "30 minutes of play daily",
        "care_notes": "Domestic breed resembling a small bobcat (no verified wild blood). Polydactylism accepted in the breed. Unusually dog-like: follows owners, rides in cars happily.",
        "diet_sensitivities": "No widespread specific sensitivities; watch tendency toward weight gain.",
        "origin": "Washington State, United States (1980s)",
        "temperament": "Laid-back, loyal, sociable, intelligent, dog-like.",
    },
    {
        "name": "Selkirk Rex",
        "size_category": "medium to large",
        "weight_range_min": 3.0,
        "weight_range_max": 7.0,
        "lifespan_years": "12-15",
        "coat_type": "Thick, plush curly coat (shorthair and longhair variants)",
        "shedding_level": "moderate to high",
        "grooming_freq": "Brush 2 times weekly gently; avoid over-grooming which flattens curls",
        "energy_level": "moderate",
        "trainability": "easy",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good",
        "common_health_issues": "Polycystic kidney disease (PKD — inherited from Persian outcrosses), HCM; generally robust otherwise",
        "exercise_needs_min": "25-30 minutes of play daily",
        "care_notes": "The 'curly sheep cat' — heavier-boned and more laid-back than other Rex breeds. Kittens' curls develop over time. Ear wax builds up; clean regularly.",
        "diet_sensitivities": "No widespread sensitivities; PKD-screened lines benefit from kidney-supportive nutrition discussions with vets.",
        "origin": "Montana, United States (1987 natural mutation)",
        "temperament": "Patient, tolerant, affectionate, playful, easygoing.",
    },
    {
        "name": "Snowshoe",
        "size_category": "medium",
        "weight_range_min": 2.7,
        "weight_range_max": 5.5,
        "lifespan_years": "12-15",
        "coat_type": "Short, smooth coat with point pattern and white 'snowshoe' feet",
        "shedding_level": "low to moderate",
        "grooming_freq": "Weekly brushing",
        "energy_level": "moderate to high",
        "trainability": "easy (learns fetch, tricks)",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good",
        "common_health_issues": "Generally healthy; may inherit Siamese tendencies (dental issues, kinked tails, crossed eyes); rare risk of HCM",
        "exercise_needs_min": "35-45 minutes of play daily",
        "care_notes": "Rare Siamese-derived breed with white mittens and inverted-V face marking. Loves water and high perches. Markings are random — each is unique. Does poorly without company.",
        "diet_sensitivities": "Occasional Siamese-line GI sensitivity; gradual food transitions advised.",
        "origin": "Philadelphia, United States (1960s)",
        "temperament": "Vocal but softer-voiced, affectionate, playful, sociable, clever.",
    },
    {
        "name": "Turkish Van",
        "size_category": "large",
        "weight_range_min": 3.5,
        "weight_range_max": 8.0,
        "lifespan_years": "12-17",
        "coat_type": "Semi-long, silky, water-resistant single coat; piebald 'Van' pattern",
        "shedding_level": "moderate",
        "grooming_freq": "Brush twice weekly (single coat resists matting); heavy seasonal sheds",
        "energy_level": "high",
        "trainability": "moderate",
        "good_with_kids": "Very good",
        "good_with_dogs": "Good with well-matched dogs",
        "common_health_issues": "Deafness risk linked to blue eyes in white areas; HCM reported rarely; otherwise a hardy natural breed",
        "exercise_needs_min": "40-50 minutes of active play daily",
        "care_notes": "Famous 'swimming cat' — genuinely seeks water. Slow to mature (3-5 years). Strong-willed and athletic; secure windows/screens. Provide a kiddie pool or dripping tap entertainment.",
        "diet_sensitivities": "No widespread sensitivities; hearty appetite matches activity.",
        "origin": "Lake Van region, Turkey",
        "temperament": "Energetic, intelligent, assertive, affectionate on own terms, playful.",
    },
    {
        "name": "Egyptian Mau",
        "size_category": "medium",
        "weight_range_min": 2.5,
        "weight_range_max": 5.0,
        "lifespan_years": "12-15",
        "coat_type": "Short, medium-fine coat with naturally occurring spots",
        "shedding_level": "low",
        "grooming_freq": "Weekly brushing",
        "energy_level": "high",
        "trainability": "moderate",
        "good_with_kids": "Very good",
        "good_with_dogs": "Good with proper introductions",
        "common_health_issues": "Pyruvate kinase deficiency, leukodystrophy (rare, DNA test available), umbilical hernia, temperature-sensitive; fastest domestic cat (48 km/h)",
        "exercise_needs_min": "40-50 minutes of running/play daily",
        "care_notes": "Only naturally spotted domestic breed. Devoted to family, wary of strangers, and extremely fast — needs safe enclosed outdoor space or indoor running room. Distinctive 'worried' facial expression and belly flap for speed.",
        "diet_sensitivities": "No widespread sensitivities; performance-level protein supports sprinter build.",
        "origin": "Egypt (landrace, formalized in Europe/US 1950s)",
        "temperament": "Loyal, shy with strangers, athletic, musical-voiced, sensitive.",
    },
    {
        "name": "European Shorthair",
        "size_category": "medium",
        "weight_range_min": 3.0,
        "weight_range_max": 6.5,
        "lifespan_years": "14-20",
        "coat_type": "Short, dense, resilient coat in nearly all colors/patterns",
        "shedding_level": "moderate to high",
        "grooming_freq": "Weekly brushing; more in shedding season",
        "energy_level": "moderate to high",
        "trainability": "moderate",
        "good_with_kids": "Very good",
        "good_with_dogs": "Good with proper socialization",
        "common_health_issues": "Very robust landrace; HCM and kidney disease appear occasionally. Few breed-specific problems due to broad gene pool.",
        "exercise_needs_min": "30-45 minutes of play/hunting-style activity daily",
        "care_notes": "Pedigreed version of Europe's common house cat (recognized mainly by FIFe). Excellent mousers with strong hunting drive — not ideal for homes with small pets. Hardy and undemanding.",
        "diet_sensitivities": "Very few; among the least allergy-prone breeds thanks to genetic diversity.",
        "origin": "Europe (Sweden/Nordic formalization)",
        "temperament": "Balanced, adaptable, independent, playful, sturdy.",
    },
    {
        "name": "Kurilian Bobtail",
        "size_category": "medium to large",
        "weight_range_min": 3.0,
        "weight_range_max": 7.0,
        "lifespan_years": "14-20",
        "coat_type": "Short or semi-long coat with pom-pom bobbed tail (each unique)",
        "shedding_level": "moderate",
        "grooming_freq": "Weekly to twice-weekly brushing",
        "energy_level": "moderate to high",
        "trainability": "easy",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good",
        "common_health_issues": "Remarkably healthy natural breed; no known widespread genetic diseases. Rare reports of anal gland impaction and struvite crystals.",
        "exercise_needs_min": "30-40 minutes of play daily",
        "care_notes": "Natural breed from Russia's Kuril Islands; superb fisher with love of water. Powerful jumper. Tail is genetically distinct from Japanese Bobtail — no spinal defects associated.",
        "diet_sensitivities": "Encourage water intake to protect urinary tract health; otherwise no widespread sensitivities.",
        "origin": "Kuril Islands, Russia/Japan",
        "temperament": "Gentle, clever, sociable, fearless, dog-like.",
    },
    {
        "name": "American Curl",
        "size_category": "small to medium",
        "weight_range_min": 2.5,
        "weight_range_max": 5.0,
        "lifespan_years": "12-16",
        "coat_type": "Silky, minimal-undercoat coat (short or long) with backward-curling ears",
        "shedding_level": "low to moderate",
        "grooming_freq": "Weekly brushing; gentle ear cleaning without forcing the cartilage",
        "energy_level": "moderate",
        "trainability": "easy",
        "good_with_kids": "Very good",
        "good_with_dogs": "Very good",
        "common_health_issues": "Ear canal narrowing (can trap wax, risk of infections); generally healthy natural-mutation breed with no widespread genetic diseases",
        "exercise_needs_min": "30 minutes of play daily",
        "care_notes": "Ears curl within days of birth and firm by ~4 months; handle cartilage gently and never force straight. Kittens born straight-eared occur in litters (curl is dominant). Adaptable and people-loving.",
        "diet_sensitivities": "No widespread sensitivities; standard premium diet appropriate.",
        "origin": "Lakewood, California, United States (1981 stray 'Shulamith')",
        "temperament": "Curious, affectionate, adaptable, people-oriented, playful.",
    },
]
