"""Veterinary condition knowledge base — additional dog conditions seed data.

Same structure as conditions_seed.py. Each entry is species-linked,
urgency-tiered, with symptoms/causes/diagnosis/treatment/prevention/
owner-actions/emergency-flags. Facts based on the Merck Veterinary Manual
with original wording throughout.
"""


def _c(species, name, slug, category, urgency, summary, symptoms, causes,
       diagnosis, treatment, prevention, breeds, actions, emergency, sources):
    return {
        "species": species, "name": name, "slug": slug, "category": category,
        "urgency": urgency, "summary": summary, "symptoms": symptoms,
        "causes": causes, "diagnosis": diagnosis, "treatment": treatment,
        "prevention": prevention, "breed_predispositions": breeds,
        "owner_actions": actions, "when_emergency": emergency, "sources": sources,
    }


CONDITIONS = [
    _c("dog", "Chocolate Toxicosis", "chocolate-toxicosis", "toxic", "emergency",
       "Poisoning from theobromine and caffeine in chocolate. Dogs metabolize theobromine far more slowly than humans, so doses that are harmless to people can cause seizures and fatal heart arrhythmias in dogs. Darker chocolate is far more dangerous than milk chocolate.",
       ["Vomiting", "Diarrhea", "Restlessness/hyperactivity", "Rapid heart rate", "Excessive thirst", "Tremors", "Seizures (severe cases)", "Collapse"],
       ["Eating baking chocolate or cocoa powder (highest risk)", "Eating dark/semisweet chocolate", "Eating milk chocolate in large quantity", "Small body size relative to dose eaten"],
       "History of ingestion plus clinical signs; heart rhythm monitoring (ECG) for arrhythmias; blood pressure and hydration assessment.",
       "Induce vomiting if recent and safe to do so (vet-supervised), activated charcoal to bind remaining toxin, IV fluids, anti-seizure medication and beta-blockers or other heart-rate control drugs as needed.",
       "Store all chocolate out of reach — counters included. Warn children and guests not to share. Watch holiday gift baskets and cocoa-based baking supplies carefully.",
       ["All dogs — no breed immunity", "Small breeds receive toxic doses from smaller amounts"],
       "Note the type of chocolate, estimated amount eaten, and time of ingestion, then call a vet or pet poison hotline immediately. Do not induce vomiting without professional guidance.",
       "Tremors, seizures, racing heartbeat, or any large dark-chocolate ingestion = emergency now. Signs may be delayed several hours but worsen progressively.",
       ["Merck Veterinary Manual — Chocolate Poisoning", "ASPCA Animal Poison Control"]),

    _c("dog", "Xylitol Toxicosis", "xylitol-toxicosis", "toxic", "emergency",
       "Poisoning from xylitol, an artificial sweetener that triggers a massive insulin release in dogs followed by life-threatening low blood sugar, and sometimes acute liver failure. Found in sugar-free gum, candy, peanut butter, and many 'sugar-free' products.",
       ["Vomiting", "Sudden weakness/collapse", "Wobbliness/incoordination", "Tremors", "Seizures", "Jaundice (liver injury stage)", "Black tarry stools (late liver damage)"],
       ["Sugar-free gum or mints", "Xylitol-sweetened peanut butter or baked goods", "Some medications, vitamins, and dental products containing xylitol", "Even small amounts are dangerous — a few pieces of gum can harm a small dog"],
       "History of exposure plus low blood glucose on a meter; liver enzyme values monitored over 24-72 hours for delayed hepatotoxicity.",
       "Immediate veterinary care: dextrose (IV sugar) to correct hypoglycemia, IV fluids, liver-protective drugs such as SAMe or silybin, and repeat glucose checks for at least 12-24 hours plus liver monitoring for days.",
       "Check labels on every sugar-free product brought home. Keep gum and purses off floors and low tables. Buy only dog-safe peanut butter. Educate household members that xylitol is lethal to dogs even in tiny amounts.",
       ["All dogs — no breed immunity", "Small dogs reach toxic thresholds fastest"],
       "If ingestion just happened, call a vet or pet poison hotline immediately — do not wait for symptoms, because hypoglycemia can develop within 30 minutes to an hour. Bring the product packaging.",
       "Any confirmed ingestion = emergency regardless of symptoms. Weakness, collapse, tremors, or seizures after eating a sugar-free product = go now; untreated hypoglycemia and liver failure are fatal.",
       ["Merck Veterinary Manual — Xylitol Toxicity", "FDA advisory on xylitol and dogs"]),

    _c("dog", "Kennel Cough (Canine Infectious Tracheobronchitis)", "kennel-cough", "infectious", "monitor",
       "A highly contagious upper respiratory infection, usually caused by a combination of bacteria (Bordetella bronchiseptica) and viruses. Produces a harsh, goose-honking cough. Most healthy adult dogs recover on their own, but puppies and immunocompromised dogs can develop pneumonia.",
       ["Dry, honking, hacking cough", "Gagging or retching after coughing fits", "Cough triggered by excitement, exercise, or leash pressure on the throat", "Clear nasal discharge", "Mild lethargy", "Fever and appetite loss (suggests complications)"],
       ["Close contact with infected dogs (boarding, daycare, shelters, grooming, dog parks)", "Stress and poor ventilation increasing susceptibility", "Incomplete vaccination status"],
       "Clinical signs plus exposure history; chest X-rays when pneumonia is suspected; PCR panels can identify the specific pathogen involved.",
       "Most cases: rest, humidified air, avoiding neck-collar pressure (use a harness), and cough suppressants prescribed by a vet. Antibiotics only where bacterial infection or pneumonia is present. Isolation from other dogs for roughly 2 weeks.",
       "Bordetella vaccination for dogs that board, attend daycare, or frequent dog parks. Choose facilities requiring vaccination with good ventilation. Keep sick dogs away from group settings entirely.",
       ["Puppies", "Brachycephalic breeds (Bulldogs, Pugs)", "Immunocompromised dogs", "Dogs in boarding/daycare/shelter settings"],
       "Keep the dog isolated from other dogs, switch to a harness, and run a humidifier or steam from a shower to ease the cough. Call your vet before arriving so they can manage contagious-dog intake.",
       "Labored breathing, blue gums, high fever, refusal of food, or a puppy that stops playing = same-day vet. Coughing with severe listlessness may mean pneumonia rather than simple kennel cough.",
       ["Merck Veterinary Manual — Canine Infectious Respiratory Disease Complex", "AVMA kennel cough information"]),

    _c("dog", "Heartworm Disease", "heartworm-disease", "parasitic", "chronic",
       "Infection with Dirofilaria immitis worms transmitted by mosquitoes. Worms mature in the heart and lung arteries over months, causing progressive heart and lung damage, and treatment of advanced disease carries real risk. Entirely preventable with monthly medication.",
       ["Persistent soft cough", "Exercise intolerance", "Fatigue after mild activity", "Weight loss", "Labored breathing (advanced)", "Swollen belly from fluid (right-heart failure)", "Sudden collapse (caval syndrome)"],
       ["Mosquito bite carrying infective larvae", "Missed or lapsed monthly preventives", "Living in or traveling to warm regions", "Outdoor lifestyle"],
       "Antigen blood test (annual screening standard), microfilaria testing, chest X-rays and echocardiogram to assess disease severity before treatment.",
       "Adulticide injections (melarsomine) given in a strict series preceded by exercise restriction; macrocyclic lactone dewormer first to clear immature stages. Exercise restriction for months is essential — exertion during worm kill-off can be fatal. Caval syndrome requires immediate surgical worm removal.",
       "Year-round monthly preventive (oral, topical, or injectable) starting in puppyhood, plus annual antigen testing even for dogs on preventives. No vaccine exists — prevention depends on consistent medication.",
       ["All dogs in mosquito-prone areas", "Outdoor dogs", "Hunting/field dogs", "Dogs in the southeastern US have highest prevalence"],
       "Never skip preventive doses. If your dog tests positive, enforce strict rest IMMEDIATELY — exercise restriction starts the day of diagnosis, before treatment begins. Follow the full treatment protocol exactly.",
       "Labored breathing, fainting, bloody urine, or sudden abdominal swelling in a known-positive dog = emergency now. These suggest caval syndrome or heart failure requiring immediate intervention.",
       ["American Heartworm Society current guidelines", "Merck Veterinary Manual — Heartworm Disease"]),

    _c("dog", "Pyometra", "pyometra", "reproductive", "emergency",
       "A life-threatening bacterial infection of the uterus filled with pus, occurring in unspayed female dogs typically weeks after a heat cycle. Hormonal changes allow bacteria to flourish. Untreated it leads to sepsis and death; spaying is both prevention and cure.",
       ["Increased thirst and urination", "Lethargy", "Vomiting", "Loss of appetite", "Pus-like vaginal discharge (open form only)", "Swollen abdomen", "Fever or abnormally low temperature", "Collapse (late)"],
       ["Unspayed status (the dominant factor)", "Repeated heat cycles without pregnancy", "Age (risk rises each cycle after middle age)", "Hormonal treatments preventing heat"],
       "Bloodwork showing elevated white cells and kidney stress, vaginal cytology, ultrasound or X-rays revealing a fluid-filled uterus.",
       "Emergency ovariohysterectomy (spay) with perioperative IV fluids and antibiotics — this is the definitive treatment even though surgery is harder on a sick patient. Medical management exists but is reserved for valuable breeding bitches and carries recurrence risk.",
       "Spay female dogs unless they are part of a managed breeding program. The disease is essentially eliminated by spaying, ideally before middle age.",
       ["Unspayed females generally", "Middle-aged and older intact females", "Bernese Mountain Dog", "Golden Retriever", "Rottweiler", "Miniature Schnauzer"],
       "Any unspayed female acting ill within 4-8 weeks of a heat cycle needs a same-day vet visit. Do not wait for discharge — the closed form (no drainage) is the most rapidly deadly because pus stays trapped inside.",
       "Vomiting plus lethargy in an unspayed bitch post-season, a distended painful belly, or collapse = emergency NOW. Sepsis develops quickly and surgical outcomes drop sharply once she is in shock.",
       ["Merck Veterinary Manual — Pyometra", "University veterinary teaching hospital pyometra outcome studies"]),

    _c("dog", "Cranial Cruciate Ligament Tear (CCL)", "ccl-tear", "orthopedic", "urgent",
       "Rupture or partial tearing of the knee ligament equivalent to the human ACL — the most common cause of rear-leg lameness in dogs. Degeneration of the ligament means many dogs tear gradually and eventually tear the other knee too. Surgery usually offers the best return to function.",
       ["Sudden three-legged lameness in a hind leg", "Toe-touching weight bearing only", "Stiffness that improves with light movement then worsens again", "Swelling (thickening) of the knee", "Difficulty rising or sitting squarely", "Muscle loss in the affected thigh over weeks"],
       ["Ligament degeneration combined with activity", "Obesity dramatically increasing load", "Conformation and genetics", "Repetitive athletic stress", "Partial tears progressing to complete rupture"],
       "Physical exam findings (cranial drawer sign, tibial compression test), radiographs to assess joint swelling and arthritic change, and sometimes arthroscopy for confirmation.",
       "Options depend on size and lifestyle: TPLO or TTA osteotomy surgeries for medium/large dogs, lateral suture (extracapsular repair) for smaller dogs, and conservative management (rest, weight loss, NSAIDs, rehab) mainly for small dogs or partial tears. Weight management and structured rehab are critical in every case.",
       "Keep dogs lean — excess weight is the single largest modifiable risk. Build muscle with steady conditioning rather than weekend-warrior bursts. Choose breeding stock screened for sound knees.",
       ["Labrador Retriever", "Golden Retriever", "Rottweiler", "Newfoundland", "German Shepherd", " Staffordshire Terrier types", "Overweight dogs of any breed"],
       "Rest the dog immediately — no running, stairs, or jumping — and book a vet exam within a few days. Note whether the opposite hind leg has ever limped, since bilateral tears are common.",
       "Complete non-weight-bearing lasting more than a day, or a knee that swells suddenly with obvious pain = prompt vet visit. While rarely an ER event itself, delays worsen arthritis; suspected tear warrants evaluation within days, not weeks.",
       ["Merck Veterinary Manual — Cranial Cruciate Ligament Rupture", "Veterinary Orthopedic Society TPLO outcome literature"]),

    _c("dog", "Cherry Eye (Third Eyelid Gland Prolapse)", "cherry-eye", "ophthalmic", "monitor",
       "Protrusion of the tear gland housed in the third eyelid, appearing as a red mass in the inner corner of the eye. Not painful initially, but the exposed gland dries out and the eye loses a major source of tear production if left uncorrected. Surgical repositioning preserves gland function.",
       ["Red/pink round mass in the inner corner of one or both eyes", "Rubbing or pawing at the eye", "Watery discharge", "Intermittent appearance then disappearance early on", "Chronic redness if long-standing"],
       ["Weak connective tissue anchoring the gland (inherited tendency)", "Both eyes often eventually affected even if only one prolapses first", "Idiopathic in most cases"],
       "Visual examination is diagnostic; the vet assesses whether the gland can be manually reduced and checks overall eye health including tear production.",
       "Surgical replacement of the gland into its pocket (pocket/Morgan-style techniques) is the standard of care — do NOT accept gland removal, which removes ~40% of tear production and predisposes to lifelong dry eye. Post-op drops and an e-collar until healed.",
       "No reliable prevention due to genetic basis. Prompt surgical correction when it occurs protects long-term tear production. Avoid breeding affected dogs.",
       ["English Bulldog", "French Bulldog", "Boston Terrier", "Beagle", "Cocker Spaniel", "Shih Tzu", "Lhasa Apso", "Great Dane"],
       "Have it assessed within a week or two — early surgery is simpler. Do not repeatedly push the gland back yourself or apply human eye drops. Use an e-collar if the dog is rubbing.",
       "While cherry eye alone is not an emergency, seek urgent care if the eye becomes cloudy, violently painful, or held shut — those signs indicate corneal injury needing immediate attention.",
       ["Merck Veterinary Manual — Third Eyelid Gland Prolapse", "ACVO (American College of Veterinary Ophthalmologists) owner resources"]),

    _c("dog", "Ear Infections (Otitis Externa)", "ear-infections-otitis", "dermatologic", "chronic",
       "Inflammation and infection of the ear canal, extremely common in dogs — especially those with floppy ears or underlying allergies. Usually driven by yeast or bacteria exploiting a moist canal environment. Recurrence is the rule unless the root cause (often allergy) is addressed.",
       ["Head shaking", "Scratching at ears", "Red, inflamed ear canal", "Odor (yeasty or foul)", "Dark brown or yellow discharge", "Head tilt or rubbing ears on furniture", "Painful reaction to touching ears", "Swelling narrowing the canal (chronic cases)"],
       ["Underlying allergies (food or environmental) — the most common driver", "Floppy ear conformation trapping moisture", "Swimming/water in canals", "Ear mites (mainly puppies)", "Foreign bodies like grass awns", "Narrowed canals from repeated infections"],
       "Otoscope examination (sedation may be needed for painful ears), cytology of discharge identifying yeast vs bacteria vs mites, culture for resistant infections, and allergy workup for recurrent cases.",
       "Thorough ear cleaning followed by prescription medicated drops matched to the cytology findings; oral antifungals/antibiotics or systemic steroids for severe inflammation. Chronic cases that scar the canal shut may need surgical canal ablation. Treat the underlying allergy to break the cycle.",
       "Dry ears after swimming/bathing, routine cleaning with vet-approved solutions for prone dogs, and investigating allergies after two or more infections per year. Never use cotton swabs deep in the canal.",
       ["Cocker Spaniel", "Basset Hound", "Labrador Retriever", "Golden Retriever", "Poodle mixes", "West Highland White Terrier", "Shar Pei"],
       "Do not start leftover drops — wrong medication with a ruptured eardrum damages hearing. Book a vet visit promptly; infections deepen and become harder to clear each week left untreated. Note diet changes and itching elsewhere to help identify allergic drivers.",
       "Severe swelling closing the canal, facial paralysis or head tilt with extreme pain, bleeding from the ear, or pain so intense the dog will not eat = urgent vet. Middle-ear involvement needs aggressive treatment.",
       ["Merck Veterinary Manual — Otitis Externa", "AAHA dermatology guidelines"]),

    _c("dog", "Skin Allergies (Atopic Dermatitis / Atopy)", "skin-allergies-atopy", "dermatologic", "chronic",
       "Genetically inherited hypersensitivity to environmental allergens — pollen, dust mites, mold — causing chronic itchy skin. One of the most common chronic diseases in dogs, typically appearing between 6 months and 3 years of age. Managed lifelong, not cured.",
       ["Persistent scratching and licking", "Chewing paws (classic sign)", "Face rubbing", "Red skin between toes", "Recurrent ear infections", "Skin darkening/thickening in chronically licked areas", "Hot spots", "Hair loss from self-trauma"],
       ["Environmental allergens absorbed through skin (pollen, dust mites, molds)", "Genetic predisposition", "Defective skin barrier allowing allergen penetration", "Food allergy coexisting in a minority of cases", "Flea allergy compounding the picture"],
       "Diagnosis is largely by ruling out fleas, food allergy, and infection first; intradermal or serum allergy testing identifies specific triggers; cytology rules in secondary bacterial/yeast infections which nearly always accompany flares.",
       "Multimodal: itch-relief drugs (oclacitinib, lokivetmab, cyclosporine), allergen-specific immunotherapy built from test results (the only approach that modifies the immune response), medicated baths, omega-3 supplements, strict year-round flea control, and treating secondary infections promptly.",
       "Cannot truly be prevented in genetically predisposed dogs, but early aggressive flea control, prompt attention to first itching episodes, fatty-acid supplementation, and regular bathing reduce flare severity. Avoid heavy breeding of affected lines.",
       ["French Bulldog", "Labrador Retriever", "Golden Retriever", "West Highland White Terrier", "Boxer", "Shar Pei", "English Bulldog", "Staffordshire Terrier"],
       "Track when flares occur seasonally to help pinpoint triggers. Keep flea control flawless — one bite can trigger a major flare. Ask about immunotherapy early instead of relying forever on escalating steroids.",
       "Raw, oozing, rapidly spreading hot spots; skin infection with fever or lethargy; or itching so severe the dog cannot sleep = prompt vet visit. Acute hot spots expand within hours and need treatment fast.",
       ["Merck Veterinary Manual — Canine Atopic Dermatitis", "International Committee on Atopic Diseases in Animals (ICADA) criteria"]),

    _c("dog", "Hypothyroidism", "hypothyroidism", "metabolic", "chronic",
       "Underproduction of thyroid hormone, usually from immune destruction of the thyroid gland. The most common hormone disorder in dogs, seen mostly in middle-aged dogs. Slows metabolism across every organ system, producing a classic picture of sluggishness and weight gain. Very treatable with daily pills.",
       ["Weight gain without increased appetite", "Lethargy/exercise intolerance", "Hair loss on tail and back of thighs ('rat tail')", "Dull dry coat with scaling", "Seeking warmth/cold intolerance", "Slow heart rate", "Recurrent skin and ear infections", "Facial 'tragic' expression from thickened skin"],
       ["Lymphocytic thyroiditis (autoimmune — most common)", "Idiopathic thyroid atrophy", "Genetic predisposition", "Rarely: thyroid tumors or treatment for hyperthyroidism"],
       "Baseline total T4 with TSH and free T4 panel (single T4 alone gives false results); thyroglobulin autoantibody testing helps clarify borderline cases. Recheck after starting therapy to fine-tune dose.",
       "Daily oral levothyroxine for life, dosed twice daily initially and adjusted by recheck bloodwork. Skin/coat improves in weeks-to-months. Dose must be reassessed periodically and after any weight change. Supplements marketed for thyroid support are not substitutes.",
       "No prevention for the autoimmune form. Annual screening of predisposed breeds from middle age catches it before significant weight gain and coat damage accumulate.",
       ["Golden Retriever", "Labrador Retriever", "Doberman Pinscher", "Cocker Spaniel", "Boxer", "Dachshund", "Great Dane", "Irish Setter"],
       "Report unexplained weight gain and dull coat rather than dismissing them as aging. Give medication consistently and on schedule; never stop once started without vet guidance. Schedule rechecks as directed — underdosing silently continues the disease.",
       "Hypothyroidism itself is rarely an emergency, but marked lethargy with a very slow pulse, collapse, or profound coldness suggests myxedema crisis, which is life-threatening and needs immediate hospitalization.",
       ["Merck Veterinary Manual — Canine Hypothyroidism", "AAHA endocrine guidelines"]),

    _c("dog", "Pancreatitis", "pancreatitis", "gastrointestinal", "urgent",
       "Inflammation of the pancreas when digestive enzymes activate prematurely and begin digesting the organ itself. Presents as sudden vomiting with abdominal pain; ranges from mild to fatal necrotizing disease. High-fat meals are a classic trigger, and repeat episodes can progress toward diabetes.",
       ["Vomiting (often repeated)", "Loss of appetite", "Hunched/praying posture from abdominal pain", "Lethargy", "Diarrhea", "Fever", "Dehydration", "Abdominal tenderness when touched"],
       ["High-fat meal or table scraps (holiday ham, bacon grease)", "Obesity", "Certain medications (some chemotherapy agents, seizure drugs)", "Hypercalcemia or hypertriglyceridemia", "Prior episodes (pancreatitis tends to recur)", "Idiopathic in many cases"],
       "Bloodwork (elevated pancreatic lipase immunoreactivity/PLI or spec cPL), abdominal ultrasound showing pancreatic swelling, and exclusion of other vomiting causes via history.",
       "Hospitalization with IV fluids, potent anti-nausea drugs, pain control, and early nutritional support (feeding sooner improves outcomes). Low-fat recovery diet on discharge. Severe necrotizing cases need intensive-care support and sometimes surgery. Lifelong fat restriction afterward.",
       "Feed no table scraps or fatty treats — ever. Keep dogs lean. Introduce any diet change gradually. Discuss medication histories with your vet to avoid pancreatitis-inducing drugs where alternatives exist.",
       ["Miniature Schnauzer (hypertriglyceridemia-linked)", "Cocker Spaniel", "Yorkshire Terrier", "Dachshund", "Poodle", "Overweight dogs of any breed"],
       "Withhold food temporarily and call the vet the same day — repeated vomiting plus a hunched painful belly should not wait overnight. Never give human painkillers. After recovery, enforce a strictly low-fat diet permanently.",
       "Continuous vomiting, rigid or intensely painful abdomen, blood in vomit/stool, or collapse = emergency now. Severe pancreatitis can shut down organs within a day or two without aggressive hospital treatment.",
       ["Merck Veterinary Manual — Canine Pancreatitis", "ACVIM consensus statement on pancreatitis"]),

    _c("dog", "Lyme Disease", "lyme-disease", "infectious", "chronic",
       "Tick-borne bacterial infection (Borrelia burgdorferi) carried by deer/black-legged ticks. Many infected dogs never show illness, but some develop shifting leg lameness, fever, and joint pain weeks after the tick bite, and a subset suffer serious kidney damage. Prevention centers on tick control.",
       ["Shifting lameness moving between legs", "Fever", "Joint swelling and pain", "Lethargy", "Reluctance to move or climb", "Decreased appetite", "Kidney-form signs: vomiting, weight loss, increased thirst (Lyme nephritis — serious)"],
       ["Attachment of an infected Ixodes (deer) tick for 24-48 hours", "Living in or traveling to endemic regions (northeastern/upper-midwestern US, Pacific coast)", "Lapsed tick prevention"],
       "Combination SNAP 4Dx screening at annual visits; confirmatory testing (quantitative C6, Lyme western blot); urine protein and kidney values checked in positives because of nephritis risk.",
       "Antibiotics (doxycycline typically) for symptomatic dogs, with improvement usually within days; positive asymptomatic dogs get kidney monitoring and a discussion about treatment. Lyme nephritis requires aggressive hospital-level therapy. Pain relief supports recovery during lameness episodes.",
       "Year-round tick preventive (topical or oral), vaccination in endemic areas where vets recommend it, daily tick checks with prompt removal (fine-tipped tweezers, straight pull), and keeping lawns/tick habitat trimmed near the house.",
       ["All dogs in endemic tick regions", "Labrador Retriever and Golden Retriever (higher Lyme nephritis risk)", "Hunting/outdoor dogs", "Dogs in wooded or tall-grass environments"],
       "Remove attached ticks promptly — transmission takes 1-2 days of feeding, so daily checks genuinely work. Report lameness with fever to your vet promptly. If your dog tests positive, keep up annual screening including urine checks.",
       "Vomiting, refusal of food, or marked lethargy in a Lyme-positive dog = urgent vet visit the same day — these can signal Lyme nephritis, which progresses fast and is life-threatening.",
       ["Merck Veterinary Manual — Lyme Borreliosis", "ACVIM consensus update on Lyme disease in dogs"]),

    _c("dog", "Periodontal Disease (Dental Disease)", "dental-disease", "dental", "chronic",
       "Progressive infection of the tissues supporting the teeth, beginning as plaque hardening into tartar and advancing to gum recession, loose teeth, bone loss, and tooth-root abscesses. Affects the majority of adult dogs by age three. Chronic pain and bacteria seeding distant organs make it far more than cosmetic.",
       ["Bad breath (halitosis)", "Yellow/brown tartar on teeth", "Red or bleeding gums", "Dropping food or chewing on one side", "Pawing at mouth", "Reluctance to chew toys/hard food", "Loose or missing teeth", "Swelling under the eye (upper tooth root abscess)"],
       ["Plaque accumulation without brushing", "Small breed crowding of teeth", "Genetics", "Soft-food-only diets", "Age", "Misaligned bites"],
       "Oral examination under anesthesia with full-mouth dental X-rays — awake 'grading' grossly understages disease because much of the pathology hides below the gumline.",
       "Professional cleaning and polishing under anesthesia with extraction or referral procedures (root planing, guided tissue repair) for diseased teeth; antibiotics only where infection warrants. Pain management around procedures. Daily home care afterward to slow reaccumulation.",
       "Daily toothbrushing with canine toothpaste (gold standard), VOHC-approved dental chews and diets as adjuncts, and regular professional cleanings sized to the individual dog's plaque rate. Start brushing in puppyhood.",
       ["Toy and small breeds (Chihuahua, Yorkshire Terrier, Maltese, Dachshund)", "Greyhound", "Shih Tzu", "Brachycephalic breeds with crowded teeth", "Dogs over 3 years generally"],
       "Look in your dog's mouth monthly and lift the lips to check back teeth. Book a dental assessment if breath turns foul. Never attempt to scale tartar yourself — anesthesia-based professional care is required for anything beyond surface plaque.",
       "Facial swelling, inability to close the jaw, refusing all food, drooling heavily, or bleeding from the mouth = prompt-to-emergency vet care. An eye-area swelling in a small dog often signals a tooth-root abscess needing urgent antibiotics.",
       ["Merck Veterinary Manual — Periodontal Disease", "AVDC (American Veterinary Dental College) position statements"]),

    _c("dog", "Heatstroke", "heatstroke", "environmental", "emergency",
       "Life-threatening overheating when a dog's cooling system (mainly panting) is overwhelmed. Body temperature above ~104-105°F begins damaging organs, and above ~106°F cell death, blood-clotting failure, and multi-organ shutdown follow rapidly. Dogs die of heatstroke in minutes, and damage continues even after cooling begins.",
       ["Heavy relentless panting", "Thick ropey drool", "Bright red gums turning pale/blue or grey", "Weakness/staggering", "Vomiting or diarrhea (often bloody later)", "Seizures", "Collapse", "Rectal temperature above 105°F"],
       ["Left in parked cars (lethal within minutes even on mild days)", "Exercise in heat/humidity", "Brachycephalic anatomy limiting panting efficiency", "Obesity", "Double coats in hot climates", "Water deprivation", "Pre-existing heart or airway disease"],
       "Clinical picture plus rectal temperature; bloodwork assessing kidney, liver, and clotting damage guides prognosis — abnormalities may take 24-72 hours to fully declare themselves.",
       "Immediate active cooling (wet towels on groin/armpits/paws, fan airflow, lukewarm — NOT ice-water immersion, which traps heat and causes shock) stopped at ~103°F to avoid overshooting; then emergency hospitalization for IV fluids, oxygen, clotting support, gastroprotection, and organ monitoring for several days.",
       "Never leave dogs in cars, period. Exercise early morning in warm weather, always provide shade and water, avoid midday humidity, use cooling vests for working dogs, and take brachycephalic or overweight dogs' limitations seriously — their margin for error is tiny.",
       ["Brachycephalic breeds (Bulldogs, Pugs, Boston Terriers)", "Overweight dogs", "Northern/double-coated breeds in hot climates", "Puppies and seniors", "Dogs with heart or airway disease"],
       "Move to shade/air conditioning, start wet-towel + fan cooling, offer small sips of water, and transport to an ER while continuing cooling. Know your dog's normal gum color beforehand so you recognize change fast. Every minute counts.",
       "Heavy panting with bright-red gums, wobbling, vomiting, or collapse in heat = EMERGENCY NOW. Even a dog that seems to recover after cooling needs emergency monitoring — organ damage peaks hours later and kills quietly.",
       ["Merck Veterinary Manual — Heat Stroke", "AVMA hot car and heat safety guidance"]),
]
