"""Veterinary condition knowledge base — additional cat seed entries.

Appended to the main conditions seed set. Same structure as
conditions_seed.py (uses the identical _c helper contract).
"""


def _c(species, name, slug, category, urgency, summary, symptoms, causes,
       diagnosis, treatment, prevention, breeds, actions, emergency, sources):
    return {
        "species": species, "name": name, "slug": slug, "category": category,
        "urgency": urgency, "summary": summary, "symptoms": symptoms,
        "causes": causes, "diagnosis": diagnosis, "treatment": treatment,
        "prevention": prevention, "breed_predispositions": breeds,
        "owner_actions": actions, "when_emergency": emergency, "sources": sources,
    }


CONDITIONS = [
    _c("cat", "Diabetes Mellitus", "diabetes-mellitus-cat", "metabolic", "chronic",
       "Insulin deficiency or resistance causing chronically elevated blood sugar. Increasingly common in indoor, overweight cats; closely related to type 2 diabetes in humans. Some cats achieve diabetic remission with early aggressive treatment and weight loss.",
       ["Increased thirst", "Increased urination (large wet clumps)", "Ravenous appetite with continued weight loss", "Lethargy", "Plantigrade stance (walking on hocks — late sign of neuropathy)", "Poor coat"],
       ["Obesity and indoor sedentary lifestyle", "High-carbohydrate dry diets", "Chronic pancreatitis", "Long-term corticosteroid use", "Male sex (2x risk)", "Increasing age"],
       "Persistently high blood glucose plus elevated serum fructosamine (distinguishes from stress hyperglycemia). Glucose in urine; ketones checked to rule out DKA.",
       "Twice-daily insulin injections (glargine or ProZinc favored in cats). Low-carbohydrate WET diet is central therapy — some cats remit on diet alone if caught early. Weight loss program. Home glucose monitoring with ear-prick meter. Untreated cats can progress to diabetic ketoacidosis.",
       "Keep your cat lean. Minimize dry kibble — low-carb canned diets dramatically cut risk. Annual bloodwork from age 8 catches early cases while remission is still achievable.",
       ["Burmese (notably in Australia/UK lines)", "Maine Coon", "Russian Blue", "Siamese", "Overweight neutered males of all breeds"],
       "Track water intake and litter box output. If insulin is started, never change dose without vet guidance; keep a consistent feeding schedule. Learn hypoglycemia signs: wobbling, weakness, seizures — rub honey/syrup on gums and call vet immediately.",
       "Vomiting, refusal to eat, rapid breathing, or collapse in a known diabetic = possible DKA or hypoglycemia — emergency either way. A cat that skips a meal on insulin is urgent.",
       ["Merck Veterinary Manual — Feline Diabetes Mellitus", "AAHA Diabetes Management Guidelines for Dogs and Cats", "International Cat Care — feline diabetes"]),

    _c("cat", "Urinary Tract Infection / FLUTD", "urinary-tract-infection-flutd", "urinary", "urgent",
       "Inflammation or infection of the bladder and urethra within the feline lower urinary tract. True bacterial UTIs are actually uncommon in young cats — most flare-ups are sterile (feline idiopathic cystitis) — but older cats and those with kidney disease or diabetes have higher infection rates. Recurrence is common and stress-linked.",
       ["Straining to urinate (small amounts)", "Frequent litter box visits with little output", "Blood-tinged urine", "Urinating outside the box (tubs, laundry, smooth surfaces)", "Excessive genital licking", "Crying while urinating"],
       ["Bacterial infection (E. coli most common — mainly senior cats)", "Feline idiopathic cystitis (stress-driven neurogenic inflammation)", "Bladder crystals/stones (struvite, calcium oxalate)", "Urine-concentrating disorders reducing natural flushing"],
       "Urinalysis (concentration, pH, blood, crystals), urine culture to distinguish true infection from sterile inflammation, imaging (X-ray/ultrasound) to rule out stones. Age-appropriate labs for underlying disease.",
       "Bacterial UTI: targeted antibiotics based on culture. Idiopathic cystitis: pain control (buprenorphine/gabapentin), increased moisture intake, environmental enrichment, and stress reduction — antibiotics add nothing without culture evidence. Stones require prescription dissolution diets or surgical removal.",
       "Feed wet food as the base diet. Multiple litter boxes (n+1 rule), scooped daily. Reduce household stressors and provide vertical space and predictable routines. Prescription urinary diets for recurrent crystal-formers.",
       ["Overweight indoor cats", "Senior cats 10+", "Cats with kidney disease or diabetes", "Persian", "Himalayan"],
       "Note urine habits before the visit — photos of accidents/clumps help. Never assume 'behavioral' — straining can precede full blockage. Increase water access immediately.",
       "Repeated straining producing NO urine, especially in a male cat = blocked cat, go to ER NOW (see urethral obstruction). Vomiting with urinary signs also escalates to emergency.",
       ["Merck Veterinary Manual — Feline Urologic Syndrome/FLUTD", "International Cat Care — FIC", "AAFP consensus statements on feline lower urinary tract disease"]),

    _c("cat", "Hairballs (Trichobezoars)", "hairballs-trichobezoars", "gastrointestinal", "monitor",
       "Accumulations of swallowed hair that form wads in the stomach because barbs prevent backward passage. Occasional hairballs are normal in grooming cats, but frequent ones signal excessive shedding, over-grooming, or impaired gut motility — and large trichobezoars can obstruct the intestine.",
       ["Retching/gagging followed by expulsion of a tubular hair mass", "Occasional vomiting of food mixed with hair", "Constipation or dry unproductive retching (impaction forming)", "Reduced appetite", "Lethargy when a mass causes partial blockage", "Bald or barbered patches (over-grooming source)"],
       ["Normal swallowing of shed fur during grooming (worse in spring molt)", "Long coat", "Underlying itchy skin disease or anxiety driving over-grooming", "Slow GI motility in older cats", "Low-fiber diets"],
       "History and exam are usually sufficient. Radiographs or ultrasound if impaction/obstruction suspected. Skin and behavior evaluation if over-grooming is suspected as the source.",
       "Most pass or are vomited up with supportive care: lubricant laxative pastes (petroleum-based), fiber supplementation, and hairball-control diets. Confirmed intestinal obstruction requires surgery. Treat any underlying skin/allergy problem fueling the grooming.",
       "Brush regularly — daily during shedding season; professional de-shedding for longhairs. Hairball-control fiber diets or pastes for chronic sufferers. Play/enrichment to displace stress-grooming. Prompt flea control (flea allergy drives licking).",
       ["Persian", "Maine Coon", "Ragdoll", "Himalayan", "Any longhaired breed", "Older cats generally"],
       "Brush more, not less. An occasional hairball (monthly-ish) is normal; weekly events warrant a vet chat. Try a lubricant paste during heavy sheds.",
       "Unproductive retching for more than 24h, complete appetite refusal, vomiting everything including water, or a painful distended belly = possible obstruction — same-day emergency.",
       ["Merck Veterinary Manual — Disorders of the Stomach in Cats", "Cornell Feline Health Center — hairballs", "International Cat Care owner resources"]),

    _c("cat", "Upper Respiratory Infection (URI)", "upper-respiratory-infection", "infectious", "urgent",
       "Cold-like infection of the nose, sinuses, and throat — overwhelmingly caused by feline herpesvirus-1 and calicivirus. Extremely contagious in multi-cat settings. Kittens can become severely ill; healthy adults usually recover, but herpesvirus stays latent for life and flares with stress.",
       ["Sneezing fits", "Clear to thick yellow-green nasal discharge", "Watery then crusty eyes", "Ulcers on tongue or lips (calicivirus hallmark)", "Fever and lethargy", "Open-mouth breathing (severe congestion — alarming in a cat)"],
       ["Feline herpesvirus-1 (rhinotracheitis)", "Feline calicivirus", "Chlamydia felis and Bordetella bronchiseptica (less common)", "Stress reactivation of latent herpesvirus", "Crowded, poorly ventilated environments (shelters, catteries)"],
       "Clinical signs are usually diagnostic; PCR panels from eye/nasal swabs identify the agent in outbreaks or chronic cases. Exam of oral ulcers and corneas (herpes causes keratitis).",
       "Supportive care is the backbone: steam/nebulization, saline nasal drops, appetite management (warmed strong-smelling food), L-lysine (mixed evidence), and fluids for dehydration. Antivirals (famciclovir) for severe herpes cases; antibiotics only when secondary bacterial infection is suspected. Kittens often need hospitalization.",
       "Core FVRCP vaccination prevents severe disease though not always infection. Quarantine new cats 2 weeks. Reduce crowding and stress. Wash hands between handling sick and healthy cats.",
       ["Kittens under 6 months", "Unvaccinated cats", "Shelter/cattery populations", "Flat-faced breeds (Persian, Exotic Shorthair — compromised drainage)"],
       "Wipe eyes/nose with warm damp cloth, run a humidifier or bring cat into a steamy bathroom, offer warmed smelly food. Isolate from other cats. Kittens eating less than usual need same-day attention.",
       "Not eating for 24h+ (hepatic lipidosis risk), open-mouth breathing, thick green discharge with fever, or a kitten going downhill = urgent vet today. Dehydration kills kittens fast.",
       ["Merck Veterinary Manual — Feline Respiratory Disease Complex", "Cornell Feline Health Center — URIs", "AAFP vaccination guidelines"]),

    _c("cat", "Tooth Resorption (FORLs)", "dental-resorptive-lesions", "dental", "chronic",
       "Progressive destruction of tooth structure by odontoclast cells — the body dissolves its own teeth, starting at the gumline. Found in 30-60% of adult cats on dental exam. Extremely painful; teeth eventually fracture and leave sharp, inflamed remnants. Cause remains unknown.",
       ["Drooling (sometimes blood-tinged)", "Chewing on one side or dropping food", "Shivering/jaw chattering when the lesion area is touched", "Reluctance to eat hard kibble despite interest", "Pawing at mouth", "Many cats show NO obvious signs — pain is chronically masked"],
       ["Unknown primary cause (odontoclast activation)", "Possible dietary/vitamin D links (under study)", "Periodontal inflammation association", "Age — incidence rises sharply after 5 years"],
       "Awake exam may reveal pink granulation tissue at the gumline, but full detection requires dental X-rays under anesthesia — resorption below the gumline is invisible otherwise. Staged by severity (types 1 and 2 guide extraction approach).",
       "There is no way to restore resorbed tooth structure: extraction of affected teeth (often crown amputation with root retention for type 2 lesions) performed by a vet under general anesthesia with radiographic confirmation. Pain control around procedures. Regular monitoring since new lesions develop over time.",
       "No proven prevention. Annual veterinary oral exams and professional dental cleaning with full-mouth X-rays catch lesions before they fracture. Brushing helps overall periodontal health but does not reliably prevent resorption.",
       ["All cats 5+", "Siamese", "Persian", "Abyssinian", "Historically reported higher in purebred lines"],
       "Watch for drooling, one-sided chewing, or kibble refusal — schedule a dental exam rather than switching foods to compensate. Budget for anesthetized dental X-rays; they are non-negotiable for diagnosis.",
       "Complete refusal of all food, heavy drooling with pawing at the mouth, or bleeding from mouth = urgent. Otherwise plan electively — but do plan, because this condition only gets worse and always hurts.",
       ["Merck Veterinary Manual — Dental Disorders of Cats", "AVDC (American Veterinary Dental College) nomenclature on tooth resorption", "Cornell Feline Health Center — dental disease"]),

    _c("cat", "Ear Mites (Otodectes cynotis)", "ear-mites", "parasitic", "chronic",
       "Contagious mites infesting the ear canal, feeding on skin debris and wax. The most common external parasite of cats and the leading cause of otitis in kittens. Intensely itchy; untreated infestation leads to secondary bacterial infections and can spread to skin folds, tail head, and other pets.",
       ["Intense scratching at ears (often until raw/scabbed)", "Profuse dry, crumbly dark brown/black debris resembling coffee grounds", "Head shaking", "Scratches/abrasions around ears and neck", "Head tilt (with secondary middle-ear involvement)", "Restlessness and irritability"],
       ["Direct contact with infested cats (mother to kitten, littermates, multi-pet homes)", "Outdoor access", "Boarding/shelter exposure"],
       "Otoscopic visualization of tiny white moving mites; microscopy of ear debris confirms. Rule out yeast/bacterial otitis which looks similar but has moister exudate. Check all pets in the household.",
       "Topical parasiticides applied at the skin (selamectin, fluralaner, moxidectin/imidacloprid) clear mites reliably — many single-dose products work. Ear cleaning removes debris. Treat ALL in-contact animals simultaneously; environment cleanup for heavily infested homes.",
       "Routine monthly broad-spectrum parasite prevention covers Otodectes. Keep new arrivals checked/quarantined. Prompt treatment prevents household spread and secondary infections.",
       ["Kittens", "Outdoor cats", "Multi-cat households", "Shelter/rescue adoptions"],
       "Never dig into the ear with cotton swabs — push debris deeper and risk eardrum damage. Get an accurate diagnosis first (mite vs. yeast vs. foreign body) before treating. Treat every pet in the house, not just the symptomatic one.",
       "Severe swelling of the ear flap (aural hematoma from violent scratching), head held tilted with stumbling, or foul-smelling pus = prompt vet visit — complications need more than an anti-mite dose.",
       ["Merck Veterinary Manual — Otitis Externa/Earmites in Cats", "Companion Animal Parasite Council (CAPC) — Otodectes", "ESAVS/BSAVA dermatology guidelines"]),

    _c("cat", "Ringworm (Dermatophytosis)", "ringworm", "infectious", "chronic",
       "Fungal skin infection (usually Microsporum canis in cats) — not a worm at all. Contagious to other animals AND humans, especially children and immunocompromised people. Long-haired cats can carry and spread it while looking nearly normal.",
       ["Circular patches of hair loss with scaling/crusting", "Broken stubbly hairs at lesion edges", "Itchiness (variable — often mild)", "Dandruff and greasy coat", "Lesions on face, ears, paws most commonly", "Sometimes no visible lesions at all (carrier state)"],
       ["Microsporum canis (most feline cases)", "Trichophyton species (less common)", "Contact with infected animals or contaminated bedding/clipper/environment (spores persist 12-18 months)", "Warm humid crowded conditions"],
       "Wood's lamp fluorescence (~50% of M. canis strains glow apple-green), fungal culture (gold standard — DTM medium), or PCR. Systemic screening in longhairs and multi-cat outbreaks via culture + toothbrush collection.",
       "Combination approach for confirmed cases: topical therapy (lime sulfur dips or miconazole/chlorhexidine shampoos twice weekly) PLUS systemic antifungals (itraconazole or terbinafine) for generalized/multi-cat cases. Environmental decontamination — mechanical removal of hair and spores matters more than any disinfectant. Culture-negative status required before stopping.",
       "Quarantine and culture new cats entering breeding/cattery situations. Isolate infected animals promptly. Vacuum and dispose of bags frequently; bleach diluted 1:10 on cleanable hard surfaces. Routine screening in Persian catteries.",
       ["Persian", "Himalayan", "Kittens", "Long-haired cats generally", "Immunocompromised animals"],
       "Isolate the cat to one easily-cleaned room, limit cuddling until treated (zoonotic!), wear gloves when applying dips, and wash hands after contact. Inform household members — human lesions start as ring-shaped rashes; see a doctor if they appear. Commit to weeks of treatment, not days.",
       "Spreading lesions despite treatment, deep crusted skin infection, fever/lethargy (systemic involvement rare), or any human in the home with expanding skin lesions = escalate care and reassess the protocol.",
       ["Merck Veterinary Manual — Dermatophytosis in Cats", "CAPC dermatophytosis guidelines", "ISCAID antifungal guidelines"]),

    _c("cat", "Feline Leukemia Virus (FeLV)", "feline-leukemia-virus", "infectious", "chronic",
       "Retrovirus that suppresses immunity and causes cancer (lymphoma/leukemia) in cats. Spread through saliva — mutual grooming, shared bowls, bite wounds, and mother-to-kitten. Once considered uniformly fatal, now understood as a spectrum: some exposed cats clear the virus, others live years as carriers with good care.",
       ["Recurrent infections (mouth, skin, respiratory)", "Weight loss and muscle wasting", "Persistent low-grade fever", "Poor coat and pale gums", "Enlarged lymph nodes", "Chronic diarrhea", "Gingivostomatitis (painful inflamed mouth)", "Often NO signs for months-years after infection"],
       ["Saliva exchange: grooming, shared food/water bowls", "Bite wounds (fighting tomcats)", "Mother to kittens (in utero or milk)", "Prolonged close cohabitation", "Kittens are vastly more susceptible than adults"],
       "ELISA antigen test (in-house SNAP test) screens for viremia; positive results confirmed by IFA (indirect immunofluorescent assay) to distinguish regressive from progressive infection. Repeat testing 30+ days after any possible exposure. CBC/biochem to stage organ impact; imaging if lymphoma suspected.",
       "No cure for the virus itself. Management centers on keeping infected cats indoors-only, aggressive early treatment of every secondary infection, excellent nutrition, parasite prevention, and regular wellness screening (twice-yearly) to catch lymphoma early. Chemotherapy works for FeLV-associated lymphoma. Supportive interferon trials have limited evidence. Avoid steroids where possible (further immune suppression).",
       "Test EVERY new cat before introducing to resident cats. FeLV core vaccine series for kittens and at-risk adults (not fully protective but valuable). Keep FeLV-positive cats strictly indoors and separated from negatives. Prevent roaming/fighting.",
       ["Kittens", "Outdoor free-roaming cats", "Males (fighting)", "Cats in multi-cat untested households"],
       "Test before you integrate — one blood test prevents lifelong regret. If your cat is positive: indoor-only, separate from negative cats, feed well, and see the vet at the FIRST hint of illness since minor problems snowball. Vaccinate household-negative companions per protocol.",
       "Rapid deterioration, refusal of food >24h, severe mouth pain preventing eating, difficulty breathing, or sudden hind-limb paralysis = immediate vet. FeLV cats crash faster than healthy cats.",
       ["Merck Veterinary Manual — Feline Leukemia Virus", "AAFP retrovirus testing and management guidelines", "Cornell Feline Health Center — FeLV"]),

    _c("cat", "Feline Immunodeficiency Virus (FIV)", "fiv", "infectious", "chronic",
       "Slow-acting lentivirus (the feline analog of HIV) that progressively weakens the immune system over years. Primarily transmitted through deep bite wounds, so outdoor intact males dominate case counts. Most FIV+ cats live near-normal lifespans indoors — this is a manageable chronic condition, not a death sentence.",
       ["Chronic/recurrent infections of skin, gums, urinary tract", "Persistent gingivostomatitis (very common)", "Slow-healing wounds", "Weight loss", "Fever of unknown origin", "Enlarged lymph nodes", "Neurologic signs in late stages", "Many cats asymptomatic for YEARS"],
       ["Deep bite wounds (primary route — saliva into tissue)", "Rare: mother to kitten, sexual contact", "Casual grooming/contact transmission is very unlikely", "Stage matters: acute phase, asymptomatic carrier years, then immune decline"],
       "Antibody ELISA/SNAP screening test; confirm positives (especially kittens, whose maternal antibodies confuse results — retest after 6 months) with Western blot or PCR. Note: vaccinating against FIV historically caused false-positive antibody tests — document vaccine history carefully.",
       "No antiviral cure in routine practice. Cornerstones: strict indoor-only living (protects the cat AND stops bites), high-quality nutrition with no raw food (immune system can't fight Salmonella), prompt aggressive treatment of infections, twice-yearly vet exams with full bloodwork, and dental care — mouths take the worst beating. AZT-type antivirals used selectively. Manage as chronic disease; many die WITH FIV, not OF it.",
       "Neuter/interrupt roaming to eliminate fighting. Introduce new cats slowly and supervise to prevent bites. Test all cats in multi-cat homes at intake. There is no widely available US vaccine currently, so bite prevention IS prevention.",
       ["Free-roaming intact male cats (up to 3x rate)", "Outdoor cats in territorial neighborhoods", "Cats with bite-wound abscess history"],
       "Get any bite wound seen promptly — early testing plus wound care matters. If your cat tests positive: keep indoors, isolate from aggressive housemates, no raw diets, and don't panic — discuss lifestyle staging with your vet rather than assuming the worst.",
       "High fever, complete appetite refusal, rapidly spreading skin infection, seizures, or severe mouth pain blocking eating = urgent evaluation. FIV cats deteriorate quickly once secondary infections take hold.",
       ["Merck Veterinary Manual — Feline Immunodeficiency Virus", "AAFP retrovirus management guidelines", "Cornell Feline Health Center — FIV"]),

    _c("cat", "Feline Asthma (Allergic Bronchitis)", "asthma-feline", "respiratory", "chronic",
       "Allergic airway inflammation causing reversible bronchoconstriction — the feline version of human asthma. Episodes range from mild cough misread as 'hairball attempts' to life-threatening respiratory crisis. Chronic inflammation remodels airways permanently if untreated.",
       ["Coughing (often mistaken for hairball retching — asthma cats crouch low with extended neck)", "Wheezing (audible on exhale)", "Labored breathing with abdominal push", "Open-mouth breathing (always abnormal in cats)", "Rapid shallow breaths", "Episodes triggered by dust/spray/litter/exertion", "Squatting posture with neck stretched out during attacks"],
       ["Inhaled allergens (pollen, dust mites, mold)", "Scented litters and aerosol sprays/perfumes", "Cigarette smoke and fireplace particulates", "Stress/exertion triggers attacks", "Genetic predisposition (Siamese overrepresented)"],
       "Radiographs show classic bronchial pattern ('donuts') and hyperinflation during episodes, though many asthmatic cats have normal films between attacks. Cytology of airway samples shows eosinophils; heartworm testing to exclude mimics. Baseline exam rules out cardiac disease.",
       "Acute attack: oxygen cage, injectable/inhaled bronchodilator (terbutaline/albuterol), fast-acting corticosteroid. Maintenance: inhaled fluticasone via spacer/mask chamber (Flovent) with albuterol rescue — preferred over long-term oral prednisolone to avoid systemic side effects. Emergency injectable epinephrine reserved for refractory crises. NEVER treat wheezing cats with just antihistamines and wait.",
       "Switch to unscented low-dust litter. Eliminate aerosols, plug-ins, incense, smoking indoors. HEPA air filtration. Maintain lean weight. Track episode frequency so medication adjustments happen BEFORE crises. Do not stop controller inhalers during quiet periods.",
       ["Siamese", "Balinese", "Young-middle-aged cats (onset typically 2-8 years)", "Overweight cats (worse symptoms)"],
       "Learn the difference between hairball retching and true coughing — film a video of an episode for your vet. Count resting breaths at home (>40/min at rest warrants a check). Keep rescue inhaler accessible; know how to use the chamber before the first crisis.",
       "Open-mouth breathing, blue/purple gums, breathing >50/min at rest with effort, or collapse = EMERGENCY — oxygen and injection now. Repeated attacks within a day despite inhaler = same-day escalation.",
       ["Merck Veterinary Manual — Allergic Bronchitis/Feline Asthma", "Cornell Feline Health Center — feline asthma", "AAFP/ISFM consensus on feline chronic airway disease"]),

    _c("cat", "Constipation & Megacolon", "constipation-megacolon", "gastrointestinal", "urgent",
       "Infrequent or difficult defecation progressing, in chronic cases, to megacolon — a permanently dilated, atonic colon that can no longer move stool at all. Dehydration drives the cycle: hard stool hurts to pass, the cat holds it, the colon stretches, and motility dies. Advanced megacolon may require surgery.",
       ["Straining in the litter box with little/no result", "Small hard dry feces (or none for days)", "Crying while attempting to defecate", "Frequent unproductive box visits (can mimic constipation AND blockage — critical distinction in males)", "Reduced appetite and vomiting as stool backs up", "Hard palpable stool column in abdomen", "Chronic cases: lethargy, hunched posture, fecal soiling"],
       ["Dehydration (kidney disease, low water intake)", "Hair ingestion/hairball obstruction", "Pelvic canal narrowing from old fractures", "Spinal disease or obesity-related reduced grooming/mobility", "Idiopathic megacolon (most common form in cats)", "Painful hips/arthritis discouraging posturing", "Medications and electrolyte imbalances"],
       "Palpation plus abdominal radiographs grade fecal load and reveal megacolon diameter, pelvic narrowing, or lumbar spine disease. Bloodwork identifies dehydration, kidney function, and electrolytes (hypokalemia worsens motility). Rule out urethral obstruction in males presenting to strain.",
       "Mild cases: subcutaneous/IV fluid therapy, stool softeners (lactulose), prokinetic agents (cisapride), and lubricant/fiber support. Recurrent impactions need veterinary enemas — NEVER give human phosphate enemas, which are lethal to cats. Refractory megacolon: subtotal colectomy with good prognosis. Lifelong management combines wet diet, hydration, and daily medication.",
       "Maximize water: all-wet diet, fountains, multiple bowls. Daily brushing reduces ingested hair. Keep cats active and lean. Manage arthritis pain so cats posture comfortably. Address early — each severe impaction stretches the colon further toward irreversible megacolon.",
       ["Middle-aged and older cats", "Manx (spinal malformations)", "Obese sedentary cats", "Cats with prior pelvic fractures", "Long-haired cats (hair ingestion)", "Cats with CKD (dehydration)"],
       "Know your cat's baseline pooping schedule and litter contents. At the first sign of hard stool: increase fluids, brush daily, ask your vet about lactulose before it compounds. Never administer human enemas or mineral oil orally (aspiration risk).",
       "No stool for 48-72h, repeated vomiting, complete appetite refusal, or a tense painful belly = urgent vet visit. In MALE cats, apparent 'straining to poop' with no urine production is a BLOCKED BLADDER — go to the ER immediately.",
       ["Merck Veterinary Manual — Constipation and Megacolon in Cats", "Cornell Feline Health Center — constipation", "ACVS Surgical Conditions — Subtotal Colectomy"]),
]
