"""Veterinary condition knowledge base — cat seed data (batch 2).

Same structured entry format as conditions_seed.py.
"""

def _c(species, name, slug, category, urgency, summary, symptoms, causes,
       diagnosis, treatment, prevention, breeds, actions, emergency, sources):
    return {
        "species": species, "name": name, "slug": slug, "category": category,
        "urgency": urgency, "summary": summary, "symptoms": symptoms,
        "causes": causes, "diagnosis": diagnosis, "treatment": treatment,
        "prevention": prevention, "breed_predispositions": breeds,
        "owner_actions": actions, "when_emergency": emergency, "sources": sources,
    }


CONDITIONS = [
    _c("cat", "Feline Anemia", "anemia-feline", "hematologic", "urgent",
       "A reduced red blood cell count leaving tissues starved of oxygen. In cats it is always a sign of something else — blood loss, immune destruction, or bone-marrow disease — and the underlying cause matters as much as the anemia itself.",
       ["Pale gums or inner eyelids", "Lethargy/weakness", "Loss of appetite", "Rapid breathing or open-mouth breathing at rest", "Seeking warm places", "Dark/tarry stools (with GI bleeding)"],
       ["Fleas or heavy external parasite load (blood loss)", "Feline leukemia virus or feline immunodeficiency virus", "Immune-mediated destruction of red cells (IMHA)", "Heinz body anemia from toxins (onion, acetaminophen, propylene glycol)", "Chronic kidney disease (reduced erythropoietin)"],
       "Packed cell volume (PCV) and complete blood count confirm anemia; reticulocyte counts show if marrow is responding. FeLV/FIV testing, Coombs test, and blood smears identify the cause.",
       "Treat the underlying disease. Severe cases need blood transfusion as a bridge. Immune-mediated anemia gets immunosuppressive drugs; kidney-related anemia may respond to darbepoetin; iron/B-vitamin support for deficiency.",
       "Year-round flea control. Keep cats indoors or supervised outdoors to limit trauma and toxin exposure. Vaccinate against FeLV for at-risk cats. Never give human pain medications to cats.",
       ["All breeds — anemia is a sign, not a breed-limited disease"],
       "Check gum color weekly in sick-appearing cats — healthy gums are pink. Any confirmed flea infestation plus lethargy warrants a vet visit, especially in kittens who can bleed out from fleas alone.",
       "Pale-to-white gums, rapid/labored breathing at rest, collapse, or dark tarry stools = same-day emergency vet. Cats compensate until they crash suddenly.",
       ["Merck Veterinary Manual — Anemia in Cats", "Cornell Feline Health Center"]),

    _c("cat", "Degenerative Joint Disease (Arthritis) in Cats", "arthritis-cats", "orthopedic", "chronic",
       "Progressive cartilage breakdown causing chronic joint pain. Radiographic evidence is found in the majority of cats over 12, yet it is dramatically underdiagnosed because cats hide pain by simply moving less instead of limping.",
       ["Reluctance or hesitation to jump up/down", "No longer sleeping on high perches", "Less grooming (matted coat over hips/back)", "Litter box misses with high sides", "Stiffness after rest, irritability when handled", "Reduced play"],
       ["Age-related cartilage wear", "Prior joint injury or developmental malformation", "Obesity increasing joint load", "Excess body weight even without primary joint disease"],
       "Diagnosis is largely clinical: owner observation questionnaires plus orthopedic exam. X-rays confirm but often underestimate pain. Rule out other causes of reduced mobility.",
       "Weight management is foundational. Solensia (frufenic monoclonal antibody against NGF) given monthly under the skin is approved for feline OA pain; gabapentin and amantadine are common adjuncts. NEVER use canine NSAIDs like meloxicam chronically in cats — toxic to kidneys. Environmental modification helps enormously.",
       "Keep cats lean throughout life. Provide ramps/steps early so jumping isn't required. Low-entry litter boxes for seniors.",
       ["Maine Coon", "Devon Rex", "Abyssinian", "Scottish Fold (cartilage defects)", "Senior cats 10+"],
       "Count how many times your senior cat jumps per day versus a year ago — declining jump behavior is the earliest sign. Raise food bowls and add steps to favorite spots before starting drugs where possible.",
       "Complete refusal to move, crying when touched, or dragging limbs = urgent same-day exam; sudden immobility could be a saddle thrombus (blood clot), not arthritis.",
       ["AAHA/AAFP 2025 feline pain management guidelines", "Merck Veterinary Manual — Degenerative Arthritis in Cats"]),

    _c("cat", "Conjunctivitis (Feline)", "conjunctivitis-cat", "ophthalmic", "monitor",
       "Inflammation of the pink membrane lining the eyelids — the most common eye problem in cats. Usually infectious (herpesvirus or chlamydia), especially in kittens, and frequently recurrent in carriers of feline herpesvirus-1.",
       ["Red, swollen eyelids", "Watery or thick discharge (clear vs yellow-green)", "Squinting/held-shut eye", "Rubbing at the face", "Third eyelid protrusion", "Both eyes affected together suggests infection"],
       ["Feline herpesvirus-1 (most common, lifelong carrier state)", "Chlamydia felis (bacterial)", "Mycoplasma", "Allergies/irritants (dust, smoke)", "Corneal ulceration secondary involvement"],
       "Fluorescein stain to check for corneal ulcers before steroid-containing drops are used. PCR panels identify herpes/chlamydia/mycoplasma when infections recur or spread through a household.",
       "Antiviral drops (cidofovir/ganciclovir) or oral famciclovir for herpes flare-ups; topical antibiotics like tetracycline clear chlamydia. L-lysine supplementation has weak evidence but is safe. Warm compresses loosen discharge.",
       "Reduce stress (multi-cat tension triggers herpes recurrences). Isolate new kittens until health-checked. Vaccination reduces but does not eliminate herpesvirus disease. Quarantine affected shelter/rescue cats.",
       ["Persian (prominent eyes prone to exposure/drying)", "Kittens in shelters/catteries", "Any cat with prior URI"],
       "Wipe discharge outward from the eye corner with a damp cotton pad. Do not use leftover human eye drops, especially steroid-containing ones — they can worsen herpetic ulcers catastrophically.",
       "Eye held fully shut, cloudy cornea, visible scratch on the eye surface, or eyeball bulging = urgent vet within hours. Corneal ulcers can perforate in a day.",
       ["Merck Veterinary Manual — Conjunctivitis in Cats", "ACVO ophthalmology guidelines"]),

    _c("cat", "Hepatic Lipidosis (Fatty Liver Disease)", "fatty-liver-hepatic-lipidosis", "hepatic", "urgent",
       "Fat infiltrates the liver when a cat stops eating, causing liver failure. The most common severe feline liver disease; it develops after just 2-7 days of anorexia, especially in overweight cats whose bodies mobilize fat rapidly.",
       ["Complete refusal to eat (often after a stressful event or diet change)", "Rapid weight loss", "Vomiting", "Drooling", "Yellow gums/eyes/skin (jaundice)", "Lethargy progressing to stupor"],
       ["Anorexia triggered by stress (new pet, moving, boarding)", "Underlying disease causing appetite loss (pancreatitis, CKD, dental pain)", "Abrupt diet change or forced weight loss in obese cats"],
       "Bloodwork shows high liver enzymes and bilirubin; ultrasound reveals the characteristic bright enlarged liver. Definitive diagnosis by fine-needle aspirate or biopsy. Rule out other liver disease concurrently.",
       "Aggressive nutritional support is THE treatment: feeding tube (nasoesophageal or esophagostomy) delivering frequent small calorie-dense meals for 2-6 weeks until self-feeding resumes. Anti-nausea meds, B vitamins, fluid support. With tube feeding, survival exceeds 80%; without it, most die.",
       "Never crash-diet an overweight cat — target 1-2% body weight loss per week with vet supervision. Minimize household stressors. Any cat not eating for 48 hours should be seen, before hepatic lipidosis sets in.",
       ["Overweight/obese domestic shorthairs", "Middle-aged cats", "Any anorexic cat regardless of body condition"],
       "Track your cat's food intake daily. If your cat skips more than two meals, call the vet immediately — do not wait for jaundice. Appetite stimulants work best started early.",
       "Not eating for 2+ days, yellowing of eyes/gums, or collapse = urgent vet today. This disease progresses from bad to fatal within a week without intervention.",
       ["Merck Veterinary Manual — Hepatic Lipidosis", "Cornell Feline Health Center"]),

    _c("cat", "Flea Allergy Dermatitis (FAD)", "flea-allergy-dermatitis", "dermatologic", "chronic",
       "An allergic reaction to flea saliva that makes a single bite trigger intense itching for weeks. The most common skin allergy in cats — often present even when owners never see fleas because cats groom them off.",
       ["Intense scratching/biting at base of tail and hindquarters", "Hair loss over rump/tail/thighs", "Small crusty sores (miliary dermatitis)", "Over-grooming with bald patches but no visible rash", "Flea dirt (black specks) on combing"],
       ["Hypersensitivity to proteins in flea saliva", "Even intermittent flea exposure maintains the reaction", "Warm humid climates extend flea season year-round"],
       "Skin exam pattern + response to rigorous flea control confirms. Intradermal or serum allergy testing rules out food/environmental allergies. Flea-combing for dirt on lower back near tail base.",
       "Modern isoxazoline oral flea preventives (fluralaner, sarolaner) kill fleas fast enough to break the cycle. Short steroid course or anti-itch monoclonal antibody breaks severe flare-ups. Treat ALL pets in home plus environment (bedding wash, carpets).",
       "Year-round flea prevention for every pet in the household — one lapse restarts infestation. Vacuum regularly, wash bedding hot. Indoor cats still get fleas (fleas ride in on humans/dogs).",
       ["All breeds; outdoor and multi-pet households highest risk"],
       "Comb your cat weekly over white paper with a fine-toothed flea comb from neck to tail base. Black specks that smear red-brown when wet = flea dirt = active infestation needing immediate treatment.",
       "Raw infected skin, open wounds from scratching, or lethargy in a heavily flea-burdened kitten (anemia risk) = prompt vet visit.",
       ["Companion Animal Parasite Council (CAPC) guidelines", "Merck Veterinary Manual — Flea Allergy Dermatitis"]),

    _c("cat", "Feline Heartworm Disease", "heartworm-cats", "cardiovascular", "chronic",
       "Lung and heart damage caused by Dirofilaria immitis worms transmitted by mosquitoes. Cats are atypical hosts: fewer worms survive, but even 1-2 worms cause severe inflammatory lung disease (HARD) with no approved cure for cats.",
       ["Coughing/wheezing resembling asthma attacks", "Difficulty breathing", "Vomiting unrelated to eating", "Weight loss", "Sudden collapse or sudden death (first sign in some cats)", "Gagging"],
       ["Mosquito bites carrying heartworm larvae", "Indoor cats get infected too (~25-33% of cases are indoor-only)", "Living in endemic regions (southeast US highest)"],
       "Antibody tests show exposure but not active disease; antigen tests miss many infections due to low worm counts. Combination of antigen + antibody testing, chest X-rays showing bronchial patterns, and echocardiography.",
       "No approved adulticide treatment for cats — management is supportive: corticosteroids reduce lung inflammation, oxygen therapy and bronchodilators during crises. Adult worms eventually die off (2-3 years) but dead worms can embolize. Some referral centers use adulticide off-label under close monitoring.",
       "Monthly heartworm prevention year-round for all cats in endemic areas (topical selamectin/moxidectin or oral milbemycin). Prevention is dramatically safer than treatment since no cure exists.",
       ["Outdoor cats in mosquito-heavy regions", "Indoor cats in endemic areas (still at significant risk)"],
       "Ask your vet about local heartworm endemicity and start monthly prevention if indicated. Never use canine heartworm products on cats — dose/toxicity differences can kill.",
       "Open-mouth breathing, blue gums, collapse, or sudden inability to stand = emergency now. Feline respiratory distress decompensates fast and can be a heartworm death event.",
       ["American Heartworm Society feline guidelines", "Merck Veterinary Manual — Heartworm Disease in Cats"]),

    _c("cat", "Feline Hyperesthesia Syndrome", "hyperesthesia-syndrome", "neurologic", "monitor",
       "A poorly understood disorder featuring rippling skin along the back, sudden frantic behavior, and self-directed aggression. Episodes look like hallucinations or panic attacks; some cases overlap with compulsive disorders or seizure activity.",
       ["Skin rippling/waving along the back", "Sudden sprinting/zoomies mid-episode", "Biting or attacking their own tail/lumbar area", "Dilated pupils and frantic vocalizing", "Tail chasing or thumping", "Episodes last 1-5 minutes then resolve abruptly"],
       ["Unknown primary cause — suspected neurologic (seizure-like focus)", "Compulsive behavioral component", "Triggered by stress/excitement", "Must rule out underlying causes first: spinal pain, allergies/fleas, myositis"],
       "Diagnosis of exclusion: full neurologic exam, spinal X-rays/MRI to rule out disc disease, dermatologic workup for pain/itch sources, trial of flea control. Video recordings of episodes from owners are extremely valuable.",
       "Anti-seizure medications (phenobarbital, gabapentin, levetiracetam) help many cats; SSRIs like fluoxetine address compulsive components. Strict routine, environmental enrichment, and reducing inter-cat tension decrease episode frequency. Avoid triggering play styles.",
       "No known prevention given unknown cause. Maintain predictable routines, provide adequate vertical space and play outlets in multi-cat homes to reduce stress triggers.",
       ["Siamese", "Burmese", "Abyssinian", "Young to middle-aged cats"],
       "Film episodes on video to show your vet — description alone often confuses this with normal zoomies or fleas. Keep an episode log with time, duration, and possible triggers.",
       "Self-mutilation (breaking skin on tail/back), seizures, or episodes clustering into continuous frenzied behavior = same-day vet evaluation.",
       ["Merck Veterinary Manual — Feline Hyperesthesia Syndrome", "Cornell Feline Health Center"]),

    _c("cat", "Panleukopenia (Feline Distemper)", "panleukopenia", "infectious", "emergency",
       "A highly contagious, frequently fatal parvovirus infection destroying white blood cells and the gut lining. Unvaccinated kittens are the classic victims; the virus survives in the environment for a year or more and resists many disinfectants.",
       ["Profound lethargy/collapse", "Vomiting", "Severe diarrhea (may be bloody)", "Total appetite refusal AND water refusal", "High fever then hypothermia late-stage", "Dehydration with sunken eyes", "Sudden death in peracute cases"],
       ["Contact with infected cats' feces/vomit", "Contaminated environments (shelters, catteries, foster homes)", "In utero infection causing cerebellar hypoplasia in surviving kittens", "Unvaccinated or incompletely vaccinated status"],
       "Clinical signs plus severely low white blood cell count on CBC is highly suggestive. Fecal antigen ELISA test (same as canine parvo test) supports diagnosis. Low platelets and elevated potassium worsen prognosis.",
       "Intensive hospitalization: IV fluids, anti-emetics, broad-spectrum antibiotics against sepsis from gut-barrier breakdown, nutritional support, sometimes transfusions. No antiviral exists. Survival ranges 20-90% depending on intensity of care; recovery grants lifelong immunity.",
       "Core FVRCP vaccine series starting at 6-8 weeks with boosters through 16+ weeks, then boosters per vet schedule — this is one of the most effective vaccines in existence. Disinfect environments with accelerated hydrogen peroxide or bleach dilution (quaternary ammonium cleaners do NOT work).",
       ["Kittens 2-6 months", "Unvaccinated adults", "Shelter/cattery populations"],
       "Isolate any suspected cat immediately and call ahead so the clinic sets up isolation intake — panleukopenia contaminates waiting rooms. Bleach-clean shared surfaces; virus persists over a year indoors.",
       "Any unvaccinated kitten vomiting and refusing food = emergency NOW. Kittens decline from walking-sick to critical within 12-24 hours; early fluids are the difference between life and death.",
       ["AVMA feline panleukopenia guidelines", "AAFP vaccination guidelines", "Merck Veterinary Manual — Feline Panleukopenia"]),

    _c("cat", "Toxoplasmosis", "toxoplasmosis-cat", "parasitic", "monitor",
       "Infection by the single-celled parasite Toxoplasma gondii. Most healthy cats show mild or no symptoms, but immunocompromised cats and kittens can develop serious disseminated disease, and cats are the definitive host spreading oocysts into the environment — the zoonotic angle drives owner concern.",
       ["Often none (healthy adult carriers)", "Fever", "Loss of appetite", "Lethargy", "Eye inflammation (uveitis)", "Neurologic signs (tremors, seizures) in disseminated cases", "Pneumonia-type breathing difficulty in severe spread"],
       ["Eating infected prey (rodents, raw meat)", "Ingestion of oocysts from contaminated soil/water", "Transplacental transmission in pregnant queens (worst outcomes in fetuses)", "Immunosuppression (FeLV/FIV co-infection) reactivating dormant cysts"],
       "Serology (IgM/IgG titers) suggests active vs past infection; PCR on tissue/fluids confirms. Diagnosis combines clinical picture, titers, and response to therapy since titers alone cannot distinguish recent from remote exposure.",
       "Clindamycin is the standard treatment, usually 2-4 weeks, effective against active disease. Supportive care for organ involvement. Eye inflammation may need topical treatment alongside systemic therapy.",
       "Keep cats indoors and feed commercial cooked diets only — no raw meat. Prevent hunting. Scoop litter boxes daily (oocysts need 1-5 days outside the cat to become infectious). Pregnant people should delegate litter duty or wear gloves and wash hands; indoor cats on cooked food pose very low risk.",
       ["Outdoor hunters", "Cats fed raw diets", "Kittens and FeLV/FIV-positive cats"],
       "Daily scooping makes household risk minimal — infectious oocysts aren't shed fresh. Pregnant household members should avoid raw-meat handling entirely (a far bigger human risk source than cats). Wash hands after gardening in soil cats may use.",
       "Seizures, difficulty breathing, or fever with eye changes in an immune-compromised cat = urgent vet. Disseminated toxoplasmosis progresses quickly without clindamycin.",
       ["CDC Toxoplasmosis fact sheets", "Merck Veterinary Manual — Toxoplasmosis", "CAPC guidelines"]),
]

