"""Veterinary condition knowledge base — seed data.

Structured entries designed for both owner guidance and professional lookup.
Each entry: species-linked, urgency-tiered, with symptoms/causes/diagnosis/
treatment/prevention/owner-actions/emergency-flags.
"""


def _c(species, name, slug, category, urgency, summary, symptoms, causes,
       diagnosis, treatment, prevention, breeds, actions, emergency, sources):
    return {
        "species": species, "name": name, "slug": slug, "category": category,
        "urgency": urgency, "summary": summary, "symptoms": symptoms,
        "causes": causes, "diagnosis": diagnosis, "treatment": treatment,
        "prevention": prevention, "breed_predispositions": breeds,
        "owner_actions": actions, "when_emergency": emergency, "sources": sources,
    }


CONDITIONS = [
    # ==================== DOGS ====================
    _c("dog", "Gastric Dilatation-Volvulus (Bloat/GDV)", "gdv-bloat", "gastrointestinal", "emergency",
       "The stomach fills with gas and can twist on itself, cutting off blood supply. GDV kills within hours without surgery. It is the single most lethal emergency in large, deep-chested dogs.",
       ["Unproductive retching", "Swollen/hard abdomen", "Excessive drooling", "Restlessness/pacing", "Panting", "Collapse"],
       ["Large meal in one sitting", "Exercise around meals", "Gulping air while eating fast", "Genetics (deep chest conformation)"],
       "X-rays show gas-distended stomach and 'double bubble' sign if twisted. Bloodwork assesses shock.",
       "Emergency decompression + surgery (derotation and gastropexy). IV fluids and shock management first.",
       "Feed 2+ smaller meals daily. Use slow-feeder bowls. No exercise 1h before/2h after eating. Preventive gastropexy at spay/neuter for high-risk breeds.",
       ["Great Dane", "German Shepherd", "Standard Poodle", "Weimaraner", "Saint Bernard", "Irish Setter"],
       "Do NOT attempt to make the dog vomit. Do not offer food/water. Transport immediately — call the ER en route so surgery team is ready.",
       "Any unproductive retching or distended abdomen in a deep-chested dog = GO NOW, even if symptoms seem mild. Hours matter.",
       ["Merck Veterinary Manual — Gastric Dilation-Volvulus", "AVMA GDV position statement"]),

    _c("dog", "Hip Dysplasia", "hip-dysplasia", "orthopedic", "chronic",
       "Malformation of the hip joint causing looseness, then arthritis over time. One of the most common inherited orthopedic diseases in dogs. Manageable but not curable without major surgery.",
       ["Bunny-hopping gait in puppies", "Difficulty rising", "Reluctance to climb/jump", "Decreased exercise tolerance", "Muscle loss in hindquarters", "Audible hip clicking"],
       ["Genetics (polygenic inheritance)", "Rapid growth in puppies", "Overfeeding/excess calcium during growth", "Excessive puppy exercise on hard surfaces"],
       "Hip X-rays (OFA/PennHIP), physical exam with Ortolani sign, breed statistics comparison.",
       "Weight management is the #1 intervention. NSAIDs, joint supplements (glucosamine/chondroitin/omega-3), physical therapy. Surgical options: FHO, double/triple pelvic osteotomy (young dogs), total hip replacement.",
       "Buy from OFA-tested parents. Keep growing puppies LEAN. Feed large-breed puppy formula. Avoid forced exercise until growth plates close (~14-18mo).",
       ["German Shepherd Dog", "Labrador Retriever", "Golden Retriever", "Rottweiler", "Great Pyrenees", "Saint Bernard", "French Bulldog", "Pug", "Bulldog"],
       "Keep your dog lean (feel ribs easily). Start joint supplements early for predisposed breeds. Report stiffness to your vet rather than chalking it up to age.",
       "Sudden non-weight-bearing, dragging rear legs, or crying when touched = same-day vet. Sudden paralysis could be IVDD, not hip pain.",
       ["OFA hip dysplasia statistics by breed", "AKC Canine Health Foundation"]),

    _c("dog", "Canine Parvovirus", "parvovirus", "infectious", "emergency",
       "Highly contagious, often fatal viral disease — especially deadly in puppies under 16 weeks. Attacks the intestinal lining and immune system. Preventable by vaccination.",
       ["Severe bloody diarrhea", "Vomiting", "Lethargy/collapse", "Fever or low temperature", "Dehydration", "Refusal of food AND water"],
       ["Unvaccinated or under-vaccinated puppies", "Contact with infected feces (environmentally persistent for years)", "Contaminated environments (shelters, parks)"],
       "Fecal ELISA antigen test (rapid, in-house). Low white blood cell count supports diagnosis.",
       "Intensive supportive care: IV fluids, anti-nausea meds, antibiotics for secondary infection. No direct antiviral. Hospitalization typically 3-7 days. Survival ~90% WITH treatment; near-zero without.",
       "Core vaccine series at 8, 12, 16 weeks. Keep puppies away from public areas until fully vaccinated. The virus survives outdoors for YEARS.",
       ["Rottweiler", "Doberman Pinscher", "American Pit Bull Terrier", "Labrador Retriever"],
       "Isolate immediately if suspected. Bleach-clean any surfaces. Tell the vet BEFORE arriving so they can use isolation entrance.",
       "Bloody diarrhea in a puppy = emergency NOW. Dehydration from parvo kills within 48-72h untreated.",
       ["AVMA Parvovirus guidelines", "AAHA vaccination protocol"]),

    _c("dog", "Intervertebral Disc Disease (IVDD)", "ivdd", "orthopedic", "urgent",
       "Spinal discs bulge or rupture, compressing the spinal cord. Ranges from back pain to full paralysis. Chondrodystrophic breeds (long-backed) are at extreme risk.",
       ["Yelping when touched/lifted", "Arched/shivering back", "Wobbling gait", "Dragging rear paws", "Knuckling over on paws", "Paralysis"],
       ["Chondrodystrophy genetics (shortened limbs)", "Jumping impacts", "Obesity", "Age-related disc degeneration"],
       "Neurological exam grades severity 1-5. MRI/spinal imaging confirms location and compression degree.",
       "Grade 1-2: strict crate rest 4-6 weeks + anti-inflammatories. Grade 3+: emergency spinal decompression surgery (best outcomes within 24h of losing deep pain sensation).",
       "Use ramps instead of jumping. Keep lean — every extra pound stresses discs. Harness instead of collar. For dachshunds: NO stairs, NO jumping off furniture, ever.",
       ["Dachshund", "French Bulldog", "Beagle", "Cocker Spaniel", "Pembroke Welsh Corgi", "Shih Tzu"],
       "If your long-backed dog yelps or wobbles: crate rest IMMEDIATELY and call vet same day. Do not let them walk it off.",
       "Dragged paws, wobbling, or loss of bladder control = surgical emergency measured in HOURS. After 24h without deep pain sensation, prognosis drops dramatically.",
       ["Merck Veterinary Manual — IVDD", "Dachshund breed health surveys"]),

    _c("dog", "Canine Diabetes Mellitus", "diabetes-mellitus", "metabolic", "chronic",
       "Insulin deficiency causing blood sugar to rise dangerously. Usually middle-aged dogs; unspayed females are over-represented. Lifelong insulin therapy after diagnosis.",
       ["Excessive thirst", "Excessive urination", "Increased appetite WITH weight loss", "Cloudy eyes (cataracts)", "Sweet/fruity breath (advanced)"],
       ["Autoimmune pancreatic destruction", "Chronic pancreatitis", "Obesity as trigger", "Genetics", "Long-term steroid use"],
       "Blood glucose curve + fructosamine test. Urinalysis shows glucose + ketones.",
       "Twice-daily insulin injections (lifelong). Consistent feeding schedule critical. Prescription diets. Spay intact females (progesterone interferes with insulin).",
       "Keep dogs lean. Spay females unless breeding. Regular vet checks catch early signs in predisposed breeds.",
       ["Australian Terrier", "Samoyed", "Keeshond", "Miniature Schnauzer", "Poodle", "Dachshund"],
       "Note water intake changes — measuring the bowl helps your vet. Never skip an insulin dose once started. Learn hypoglycemia signs (weakness, wobbling): rub corn syrup on gums if seen.",
       "Collapse, seizures, or fruity-smelling breath = emergency now. Diabetic ketoacidosis is life-threatening.",
       ["Merck Veterinary Manual — DM", "AAHA diabetes management guidelines"]),

    _c("dog", "Canine Bloat Risk Management", "bloat-risk-management", "preventive", "monitor",
       "Not a condition itself — this entry tracks preventive strategy for GDV-prone dogs. See GDV entry for the emergency itself.",
       ["Deep chest confirmation (chest depth > width)", "Family history of bloat", "Fast eating habits", "Once-daily large meal feeding"],
       ["Anatomy + behavior combined risk profile"],
       "Risk assessment by breed, chest depth measurement, family history review.",
       "Elective prophylactic gastropexy (stomach-tacking surgery) reduces GDV mortality risk dramatically. Can be done laparoscopically at time of spay/neuter.",
       "Prophylactic gastropexy discussion with vet for all deep-chested breeds. Slow-feeder bowls, multiple small meals, rest around mealtimes.",
       ["Great Dane", "Weimaraner", "Standard Poodle", "German Shepherd", "Irish Setter"],
       "Schedule gastropexy conversation with your vet if your breed is listed in GDV entry.",
       "N/A — preventive entry. See GDV for emergency signs.",
       ["Purdue University GDV risk factor study"]),

    # ==================== CATS ====================
    _c("cat", "Urethral Obstruction", "urethral-obstruction", "urinary", "emergency",
       "Blockage of the urethra preventing urination. Male cats are at highest risk due to narrow urethra. Fatal within 24-48 hours untreated. THE most time-critical feline emergency.",
       ["Repeated straining with no urine", "Frequent litter box visits", "Crying/vocalizing in box", "Licking genitals excessively", "Vomiting", "Lethargy progressing to collapse", "Hard painful belly"],
       ["Crystals/stones blocking urethra", "Urethral plug (mucus + minerals)", "Stress-related inflammation (FIC)", "Diet"],
       "Physical exam (firm painful bladder), bloodwork for kidney values and potassium (life-threatening levels), X-ray/ultrasound for stones.",
       "Emergency urinary catheterization under sedation, IV fluids to flush potassium, hospitalization 2-4 days. Surgery (perineal urethrostomy) for repeat blockers.",
       "Feed wet food (increases water intake). Water fountains encourage drinking. Reduce stress (multi-cat households need multiple litter boxes). Prescription urinary diets for stone-formers.",
       ["Male cats of ALL breeds", "Overweight cats", "Indoor-only cats", "Persian (stone-forming lines)"],
       "If you even SUSPECT your male cat isn't peeing — go to the ER now. Do not wait to see if he goes later. Potassium rises kill within 24h.",
       "No urine produced despite straining, vomiting, or collapse. A blocked cat that stops vocalizing is getting WORSE not better.",
       ["International Cat Care — FLUTD", "Merck Veterinary Manual — UO"]),

    _c("cat", "Lily Toxicosis", "lily-toxicosis", "toxic", "emergency",
       "ALL parts of true lilies (Easter, Tiger, Day, Stargazer) cause fatal acute kidney failure in cats. Even grooming pollen off fur or drinking vase water is lethal. There is no safe exposure level.",
       ["Vomiting within hours", "Depression", "Loss of appetite", "Increased thirst (early kidney damage)", "Tremors", "No urination (kidney failure stage)"],
       ["Easter lily", "Tiger lily", "Daylily", "Stargazer lily", "Asiatic lily", "Any Lilium or Hemerocallis species"],
       "History of exposure + rising creatinine/BUN on bloodwork within 24-72h. Urine concentration testing.",
       "AGGRESSIVE IV fluid diuresis for 48-72h — started early (within 18h of ingestion), kidneys usually survive. Delayed treatment often means dialysis or euthanasia.",
       "NEVER keep true lilies in a home with cats. Check bouquets before bringing inside. Educate gift-givers. Safe alternatives: roses, sunflowers, orchids.",
       ["ALL CATS — no breed immunity"],
       "If you see pollen on fur or suspect chewing: rinse mouth with water, wipe coat with damp cloth, go to ER immediately. DO NOT WAIT FOR SYMPTOMS — early fluids save lives.",
       "Any known exposure = emergency regardless of symptoms. Once vomiting starts, kidney damage has begun.",
       ["ASPCA Animal Poison Control", "Journal of AVMA — lily toxicosis studies"]),

    _c("cat", "Hyperthyroidism", "hyperthyroidism", "metabolic", "chronic",
       "Overactive thyroid gland flooding the body with metabolism hormone. The most common endocrine disease of older cats (>8 years). Treatable when caught, fatal when ignored.",
       ["Weight loss WITH good/ravenous appetite", "Increased thirst/urination", "Vomiting", "Diarrhea", "Hyperactivity/restlessness at night", "Fast heart rate", "Poor coat"],
       ["Benign thyroid adenoma (98% of cases)", "Environmental toxin exposure theories (flame retardants)", "Iodine dietary factors (under study)"],
       "Blood T4 level (elevated confirms). Blood pressure check (hypertension common companion). Kidney values MUST be evaluated simultaneously.",
       "Options: daily methimazole medication, radioactive iodine therapy (curative, one-time), surgery, prescription iodine-restricted diet (y/d). Kidney function must be monitored post-treatment — treating hyperthyroidism can unmask hidden kidney disease.",
       "No known prevention. Annual senior bloodwork (7+) catches it early before organ damage.",
       ["Siamese", "Himalayan", "Older cats generally"],
       "Track weight monthly — weight loss with good appetite in an older cat warrants bloodwork. Don't attribute to 'just getting old.'",
       "Refusing food, severe vomiting, difficulty breathing, or hind-limb weakness (blood clot from heart disease) = immediate vet.",
       ["Merck Veterinary Manual — Feline Hyperthyroidism", "AAFP senior care guidelines"]),

    _c("cat", "Chronic Kidney Disease (CKD)", "chronic-kidney-disease", "metabolic", "chronic",
       "Progressive, irreversible loss of kidney function. Affects up to 30% of cats over 15. Managed (not cured) — early detection dramatically extends quality lifespan.",
       ["Increased thirst", "Increased urination (large clumps in litter)", "Weight loss", "Decreased appetite", "Bad breath (ammonia)", "Vomiting", "Poor coat", "Lethargy"],
       ["Age-related degeneration", "Prior kidney injury (lilies, antifreeze)", "Polycystic kidney disease (genetic)", "Chronic infections", "Hyperthyroidism masking/mimicking"],
       "Bloodwork (creatinine, SDMA — earlier marker), urinalysis concentration, ultrasound for structure. IRIS staging system guides treatment intensity.",
       "Prescription renal diets (proven to extend lifespan), phosphorus binders, subcutaneous fluids at home, appetite stimulants, anti-nausea meds, potassium supplements. Stage-appropriate management.",
       "No prevention for age-related CKD. Annual/senior screening catches stage 1-2 when interventions work best. Keep hydrated (wet diet). Avoid nephrotoxic drugs.",
       ["Persian", "Maine Coon", "Abyssinian", "Russian Blue", "Senior cats 10+"],
       "Learn your cat's normal water consumption. Switching to wet food is the single best preventive step. Annual senior panels from age 8.",
       "Complete appetite refusal, severe vomiting, or collapse = urgent. Dehydration spirals fast in CKD cats.",
       ["IRIS (International Renal Interest Society) staging", "International Cat Care CKD toolkit"]),

    # ==================== HORSES ====================
    _c("horse", "Colic", "colic", "gastrointestinal", "emergency",
       "Abdominal pain from any cause — gas, impaction, displacement, or torsion (twist). The leading natural cause of death in horses. Some colic resolves medically; some requires emergency surgery within hours.",
       ["Pawing at ground", "Looking/biting at flank", "Rolling or attempting to roll", "Stretching like to urinate", "Loss of appetite", "No gut sounds", "Sweating", "Kicking at belly"],
       ["Grain overload", "Sand ingestion from grazing", "Sudden feed change", "Dehydration", "Parasites", "Impaction from poor teeth/dehydration", "Displacement/torsion (surgical)"],
       "Vet exam: gut sounds (4 quadrants), gum color/refill, heart rate (key indicator), rectal palpation, nasogastric tube reflux check, ultrasound. Reflux + severe pain = surgical candidate.",
       "Medical: nasogastric mineral oil, IV fluids, pain relief (Banamine). Surgical: emergency celiotomy — survival best when operated within 6h of refractory pain.",
       "Consistent feeding schedule. Max forage/min grain. Clean water ALWAYS (heated in winter). Regular dental floats. Parasite control program. Sand-clear for sandy-soil regions. Don't graze hungry horses on lush pasture.",
       ["All horses — no breed immunity", "Thoroughbreds statistically higher surgical colic rates"],
       "Remove all food. Call vet IMMEDIATELY (don't wait through one bad night). Walk horse slowly if safe — do not let roll. Note last manure, water intake, any feed changes for the vet.",
       "Refractory rolling, no gut sounds, HR >60, purple/grey gums, reflux up the nose tube = likely surgical colic. Transport to surgical facility NOW.",
       ["AAEP colic guidelines", "Equine Veterinary Journal colic survival studies"]),

    _c("horse", "Laminitis", "laminitis", "orthopedic", "emergency",
       "Inflammation of the laminae bonding hoof wall to coffin bone. In severe cases the bone rotates or sinks — permanent crippling or euthanasia. Prevention is everything because damage is irreversible.",
       ["Heat in hooves", "Strong digital pulse", "Leaning back weight stance ('camped out')", "Reluctance to move/turn", "Standing soreness", "Visible founder rings on hooves"],
       ["Carbohydrate overload (grain breach, lush pasture)", "PPID (Cushing's) in seniors", "Insulin dysregulation/EMS", "Concussion (hard surfaces)", "Sepsis-associated"],
       "Clinical signs + radiographs to assess bone rotation. Insulin testing if EMS suspected.",
       "Remove cause (off grass, no grain). Soft deep bedding. Vet-prescribed NSAIDs. corrective trimming/shoeing. Severe cases need specialized farriery or hospital treatment.",
       "LIMIT pasture access for easy keepers/EMS horses (grazing muzzle). No grain unless working hard. Treat PPID aggressively. Annual vet + farrier partnership.",
       ["Pony breeds", "Morgan", "Haflinger", "Miniature Horse", "Easy keepers of any breed", "Horses with PPID/Cushing's"],
       "Pull off grass immediately, provide soft footing, call vet today. Do not force walking. Note what they ate recently.",
       "Reluctance to move at all, visible rotation on X-ray, or any laminitis in a horse already EMS/PPID diagnosed = aggressive intervention now.",
       ["AAEP Laminitis guidelines", "University of Pennsylvania laminitis research"]),

    _c("horse", "Equine Strangles", "strangles", "infectious", "urgent",
       "Highly contagious bacterial infection (Streptococcus equi) causing abscessed lymph nodes. Spreads like wildfire through barns. Rarely fatal but devastating to operations — quarantine lasts weeks.",
       ["Thick yellow nasal discharge", "Fever", "Swollen/abscessed lymph nodes under jaw", "Difficulty swallowing", "Depression", "Loss of appetite", "Cough"],
       ["Direct contact with infected horse", "Shared water buckets/equipment", "Human clothing/hands as vector", "Contaminated environment (bacteria persists months)"],
       "PCR from nasal wash or guttural pouch lavage. Blood work shows high white cells. Guttaural pouch endoscopy for carriers.",
       "Supportive care: hot-packing abscesses to mature, soft feeds, NSAIDs. ANTIBIOTICS CONTROVERSIAL — may prolong carrier state. Quarantine 3+ weeks after last fever.",
       "New arrivals quarantined 2-3 weeks minimum. No shared equipment. Temperature monitoring at shows. Vaccination for high-risk operations (intranasal).",
       ["Young horses (1-5yr)", "Frequently-traveled/show horses", "Boarding facilities"],
       "ISOLATE IMMEDIATELY — do not wait for confirmation. Stop all barn traffic. Take temperatures of every horse twice daily. Call vet to design quarantine protocol.",
       "Difficulty breathing (retropharyngeal abscess), spreading to other organs ('bastard strangles'), or any new horse developing fever = escalate immediately.",
       ["AAEP strangles guidelines", "State veterinary quarantine protocols"]),

    # ==================== CATTLE ====================
    _c("cattle", "Frothy Bloat", "frothy-bloat", "gastrointestinal", "emergency",
       "Gas trapped in stable foam the animal cannot belch out. Left flank swells visibly. Death from pressure on diaphragm within 2-4 hours in severe cases.",
       ["Distended left flank (LHS para-lumbar fossa)", "Stop eating/ruminating", "Discomfort/kicking at belly", "Open-mouth breathing (late)", "Staggering (late)"],
       ["Lush legume pasture (alfalfa/clover)", "Fine-particulate grain overload", "Sudden ration change"],
       "Visual + palpation of left flank distension, rumen puncture site assessment, history of pasture/grain change.",
       "Stomach tube to relieve gas. Anti-foaming agents (poloxalene, vegetable oil). Trocar/cannula in life-threatening cases. Walk the animal slowly if able.",
       "Gradual pasture transitions (never starve onto alfalfa). Poloxalene supplement before turnout on lush legume. Bloat-resistant forage varieties. Limit grain access with gradual introduction.",
       ["All cattle on legume pasture", "Feedlot cattle on high-grain rations"],
       "Remove from pasture immediately. Walk slowly. If severely distended and struggling to breathe, this needs emergency intervention NOW — call the vet on the way.",
       "Animal going down, open-mouth breathing, or severe distension = minutes matter. Emergency trocar may be needed on-site.",
       ["Merck Veterinary Manual — Pasture Bloat"]),

    _c("cattle", "Milk Fever (Hypocalcemia)", "milk-fever", "metabolic", "emergency",
       "Blood calcium crash at calving (typically within 72h). Older, higher-producing cows are highest risk. Rapidly progressive from staggering to full recumbency to death.",
       ["Staggering/wobbly gait", "Muscle tremors", "Cold ears/extremities", "Down and unable to rise (classic S-curve neck)", "Dry muzzle", "Constipation", "Reduced rumen contractions"],
       ["Calcium drain into colostrum exceeding body reserves", "Older cows (3rd+ lactation)", "Jerseys more susceptible relative to size", "Pre-calving high-calcium diet paradoxically increases risk"],
       "Clinical signs + stage of lactation history. Response to IV calcium is diagnostic and therapeutic simultaneously.",
       "IV calcium borogluconate SLOWLY (heart monitoring — too fast kills). Oral calcium gel for milder cases. Most stand within 30min-2h of correct treatment.",
       "DCAD (negative dietary cation-anion difference) pre-fresh diet — the key prevention. Oral calcium boluses at calving for high-risk cows. Avoid high-calcium pre-fresh rations.",
       ["Jersey", "Older cows (3+ lactations)", "High-producing dairy breeds"],
       "If a fresh cow is down: get her sternal (not lateral), call vet for IV calcium. Oral calcium only if she can swallow safely. Recurrence possible within days — monitor closely.",
       "Down cow that doesn't respond to initial calcium, bloating from lateral recumbency, or muscle damage from prolonged down time = escalate. Down cow syndrome has compounding losses hourly.",
       ["Merck Veterinary Manual — Parturient Paresis"]),

    # ==================== GOATS ====================
    _c("goat", "Barber Pole Worm Anemia (Haemonchus contortus)", "barber-pole-anemia", "parasitic", "emergency",
       "Blood-sucking stomach worm causing severe anemia. The #1 killer of goats in warm/wet climates. Worms don't show in fecal floats reliably (they're blood-suckers, not egg-shedders proportionally) — FAMACHA eye scoring is the tool.",
       ["Pale/white inner eyelids (FAMACHA score 4-5)", "'Bottle jaw' (swelling under chin)", "Lethargy", "Weight loss despite appetite", "Weakness/staggering", "Death without obvious prior illness"],
       ["Warm wet climates favor larvae", "Overgrazed pastures (larvae low on grass)", "No effective deworming rotation", "Resistance to common dewormers"],
       "FAMACHA eyelid score (1=red healthy to 5=white critical), fecal egg count, packed cell volume for severity.",
       "Effective dewormer based on farm resistance profile (rotate classes, use combination treatments). Iron support. Prohibit grazing recovery period. Severe cases may need transfusion.",
       "FAMACHA score every 2 weeks in season — treat ONLY anemic animals (selective refugia slows resistance). Rotate pasture species (cattle/horses co-grazing cleans goat parasites). Avoid overstocking. Breed for resistance.",
       ["All goats in warm/humid regions", "Kids and pregnant does most vulnerable"],
       "Check inner eyelid color NOW if bottle jaw or lethargy present. White lids = emergency deworming + iron + vet. Do NOT blanket-deworm the whole herd — resistance makes this worse long-term.",
       "FAMACHA 4-5, recumbency, or bottle jaw in a pregnant doe = emergency. Anemic goats die of hypoxia quickly.",
       ["American Consortium for Small Ruminant Parasite Control (ACSRPC) — FAMACHA system", "Southern Consortium worm resistance studies"]),

    _c("goat", "Pregnancy Toxemia (Ketosis)", "pregnancy-toxemia", "metabolic", "emergency",
       "Energy crisis in late-pregnancy does carrying multiple kids. The doe can't eat enough to fuel fetal glucose demand, breaks down fat, and poisons herself with ketones. Kills mom AND kids if untreated.",
       ["Lethargy in final 4-6 weeks", "Off feed", "Sweet/acetone breath", "Grinding teeth", "Separating from herd", "Blindness/stargazing (late)", "Recumbency", "Neurologic signs"],
       ["Multiple fetuses (twins+ demand)", "Overfat OR underfed does", "Late pregnancy stress", "Inadequate late-gestation nutrition"],
       "Blood ketone/glucose testing (meter works), urine ketostix, history of late pregnancy + multiples.",
       "Oral propylene glycol 3-4x daily (60ml doses), IV dextrose in severe cases, induce labor if viable (kids die anyway if mom dies — C-section sometimes indicated). Calcium often needed concurrently.",
       "Increase grain steadily in last 4-6 weeks (energy density matters, not just volume). Ultrasound for kid count to identify high-risk does. Do not let does get fat pre-breeding. Easy access to best hay.",
       ["Does carrying twins/triplets+", "Overconditioned or thin does", "First-time mothers with poor body condition"],
       "Start propylene glycol immediately (available at feed stores) and call vet. This progresses to coma in 24-48h. Every hour counts for saving doe and kids.",
       "Recumbency, neurologic signs, or refusal of propylene glycol = C-section/immediate intervention territory. Dead kids = dead mom without surgery usually.",
       ["Merck Veterinary Manual — Pregnancy Toxemia", "Maryland Small Ruminant Page protocols"]),
]
