"""Large animal conditions — horses, cattle, goats."""


def _c(species, name, slug, category, urgency, summary, symptoms, causes,
       diagnosis, treatment, prevention, breeds, actions, emergency, sources):
    return {
        "species": species, "name": name, "slug": slug, "category": category,
        "urgency": urgency, "summary": summary, "symptoms": symptoms,
        "causes": causes, "diagnosis": diagnosis, "treatment": treatment,
        "prevention": prevention, "breed_predispositions": breeds,
        "owner_actions": actions, "when_emergency": emergency, "sources": sources,
    }


M = "Merck Veterinary Manual"

HORSE_CONDITIONS = [
    _c("horse", "Tying-Up (Azoturia / EPSM)", "tying-up", "musculoskeletal", "emergency",
       "Severe muscle cramping during exercise with muscle breakdown products spilling into urine. Can permanently damage kidneys. Also called exertional rhabdomyolysis; chronic forms linked to polysaccharide storage myopathy.",
       ["Stiff, stilted gait during work", "Firm painful back/hindquarter muscles", "Sweating unrelated to effort", "Dark brown/red urine", "Reluctance to keep moving"],
       ["Excess grain with no exercise", "Electrolyte imbalances", "Vitamin E/selenium deficiency", "Genetic polysaccharide storage myopathy"],
       "Blood tests for CK and AST muscle enzymes; urine color. Genetic testing for PSSM1 available.",
       "STOP all exercise immediately. Cover with blanket. Do NOT walk it out. IV fluids to flush kidneys, NSAIDs for pain, vitamin E supplementation. Chronic cases need diet/exercise overhaul.",
       "Low-starch high-fat diet (no grain), consistent daily exercise without days off, electrolyte balance, vitamin E/selenium per soil region.",
       ["Quarter Horse (PSSM1)", "Draft breeds", "Warmbloods", "Thoroughbreds (sporadic form)"],
       "Stop work instantly — moving a tying-up horse worsens muscle damage. Offer water. Call vet; dark urine means kidney involvement.",
       "Red/brown urine, refusal to move entirely, or colic-like signs alongside cramping = emergency now.",
       [M, "AAEP lameness/myology resources"]),
    _c("horse", "Equine Gastric Ulcer Syndrome", "equine-gastric-ulcers", "gastrointestinal", "chronic",
       "Ulceration of the stomach lining — affects up to 90% of racehorses and a majority of performance horses. Continuous grazers evolved to produce acid constantly; concentrated meals and empty stomach periods cause damage.",
       ["Poor appetite / picky eating", "Grinding teeth (bruxism)", "Girthiness / reacting to girthing", "Poor coat/condition despite good feed", "Mild recurrent colic signs", "Attitude changes under saddle"],
       ["High-grain low-forage diets", "Intense training", "Long periods without forage", "Stress (transport, showing, stall confinement)", "Frequent NSAID use (Bute)"],
       "Gastroscopy is the only definitive test (fasting required). Response-to-treatment trial also used in practice.",
       "Omeprazole (FDA-approved, 4-week course at treatment dose then maintenance). Diet change is essential or ulcers return: continuous hay access, reduced starch, alfalfa helps buffer acid.",
       "Free-choice forage 24/7, small frequent feeds, reduce grain, alfalfa portion, turnout maximization, omeprazole before known stressors (transport/showing).",
       ["Racehorses", "Show/performance horses", "Stall-confined horses of any breed"],
       "Discuss gastroscopy with your vet if your horse shows these signs chronically. Don't mask with painkillers long-term — Bute itself causes ulcers.",
       "Colic signs plus known ulcer history could indicate severe ulceration/perforation = immediate vet.",
       [M, "Consensus statement on EGUS (Journal of Equine Veterinary Science)"]),
    _c("horse", "West Nile Virus", "west-nile-fever", "infectious", "urgent",
       "Mosquito-borne viral encephalitis. Vaccination is highly effective — most severe cases occur in unvaccinated horses. Not contagious horse-to-horse.",
       ["Fever", "Ataxia (wobbliness) — often asymmetric", "Muscle twitching/fasciculations", "Hypersensitivity to touch", "Lip drooping/tongue weakness", "Recumbency in severe cases"],
       ["Mosquito bites from infected birds (reservoir host)", "Late summer/fall peak", "Unvaccinated status"],
       "Serology (IgM capture ELISA) plus clinical signs; ruling out other encephalitides.",
       "Supportive care: NSAIDs, IV fluids, anti-inflammatories (DMSO), slinging if recumbent. Most vaccinated-or-mild horses recover; severe neurologic cases may not.",
       "Annual vaccination (spring, before mosquito season) is the core defense. Mosquito control: eliminate standing water. Report suspected cases — state reportable disease.",
       ["All horses — no breed predisposition", "Highest risk: unvaccinated"],
       "Isolate from other horses pending diagnosis (rule-outs include contagious diseases). Call vet same day for neurologic signs.",
       "Down/inability to rise, seizure, or rapid worsening of wobbliness = emergency referral.",
       [M, "USDA APHIS West Nile guidelines", "AAEE vaccination guidelines"]),
    _c("horse", "Equine Influenza", "equine-influenza", "infectious", "monitor",
       "Highly contagious respiratory virus — the 'flu' of horses. Spreads rapidly through barns and shows via aerosol. Rarely fatal in healthy adults but knocks horses out of work for weeks.",
       ["Dry harsh cough (hallmark sign)", "Fever", "Clear nasal discharge becoming thick", "Enlarged submandibular lymph nodes", "Depression", "Loss of appetite"],
       ["Aerosolized virus from coughing horses", "New arrivals shedding without symptoms", "Unvaccinated or lapsed-vaccine horses", "Shared equipment/transport"],
       "Clinical signs + PCR from nasal swab. Serology for confirmation.",
       "Rest is the critical component — minimum 3 weeks, longer for complications risk. NSAIDs for fever. Antibiotics only for secondary bacterial infection (thick green discharge, persistent fever).",
       "6-month vaccination interval for competition horses. Biosecurity: quarantine new arrivals 14 days, no sharing buckets/tack. Outbreak protocol: stop all movement.",
       ["Young horses (2-3yr)", "Frequently traveling/competing horses", "Unvaccinated barn-mates"],
       "Stop riding immediately, isolate the horse, take temperatures of every horse on premises twice daily, call vet. Cough spreads it 30+ meters through air ducts.",
       "Pneumonia signs (labored breathing, purple gums) or myocarditis signs after flu (poor performance post-recovery) warrant urgent reassessment.",
       [M, "OIE equine influenza expert surveillance panel"]),
    _c("horse", "Sand Colic", "sand-colic", "gastrointestinal", "urgent",
       "Sand accumulation in the gut from grazing on sandy soils or eating off the ground. Sand accumulates gradually causing intermittent colic, weight loss, or diarrhea. Common in coastal/desert regions.",
       ["Intermittent mild colic episodes", "Diarrhea (sometimes sand-laden)", "Gradual weight loss despite appetite", "Gurgling sounds at the bottom of the belly", "Sand visible in manure"],
       ["Grazing sandy/dry pastures where roots carry sand", "Eating off sandy ground", "Feeding on ground in sandy paddocks", "Insufficient long-stem forage"],
       "Auscultation of lower flank for sand sounds (glass-of-water trick), fecal sedimentation test, abdominal ultrasound/radiographs quantify burden.",
       "Psyllium husk courses (1 cup/day for 1 week each month) help clear modest loads. Heavy burdens need mineral oil/magnesium sulfate via stomach tube by vet. Surgery rarely needed but possible for impaction.",
       "Feed off rubber mats/elevated feeders, never directly on sand. Psyllium monthly in sandy areas. Adequate long-stem hay keeps gut moving. Avoid overgrazed short pastures on sandy soil.",
       ["All breeds in sandy-soil regions (Florida, Texas, California, desert Southwest)"],
       "If your horse lives on sand and shows any colic signs, mention sand exposure to the vet. Fecal sand test at home: manure in water jar, watch what settles.",
       "True painful colic episode in a sand-exposed horse = vet visit today; impaction may require intervention.",
       [M, "University extension sand colic protocols"]),
    _c("horse", "Corneal Ulcer (Eye Ulcer)", "eye-ulcer-equine", "ophthalmologic", "emergency",
       "Break in the corneal surface that can deepen to rupture within 24-48 hours. Horse eyes are enormous and fragile. What looks minor can be blinding fast — equine eyes are always urgent.",
       ["Squinting/closed eye", "Heavy tearing", "Cloudy white/blue spot on cornea", "Light sensitivity", "Swollen eyelid", "Rubbing eye on leg/objects"],
       ["Trauma (hay awn, branch, dust)", "Facial nerve paralysis preventing blinking", "Insect irritation", "Uveitis predisposition (Appaloosas)"],
       "Fluorescein dye stain reveals the ulcer; ophthalmic exam assesses depth. Deep ulcers need culture.",
       "Frequency topical antibiotics (initially every 2-4 hours round-the-clock), atropine for pain/spasm, serum therapy. Deep/infected ulcers may need surgical graft. NEVER use steroid eye meds without diagnosis.",
       "Fly masks in insect season, remove sharp objects from stalls/doorways, prompt attention to any tearing/squinting — early ulcers heal fast, deep ones don't.",
       ["Appaloosa (uveitis → secondary ulcers)", "Horses with white faces/pink eyelids", "Horses kept in dusty environments"],
       "Any squinting or cloudy eye = vet SAME DAY. Do not wait overnight. Do not apply leftover eye medications — steroids can melt an ulcer if herpetic/fungal.",
       "Corneal cloudiness spreading, eye appearing to bulge, or ulcer deepening on recheck = emergency surgical evaluation.",
       [M, "AAEP ophthalmology resources"]),
    _c("horse", "PPID (Equine Cushing's Disease)", "cushings-ppid", "endocrine", "chronic",
       "Pars intermedia dysfunction — the pituitary gland loses dopamine control, causing hormone excess. The most common endocrine disease of older horses (>15yr). Manageable lifelong with medication; untreated leads to laminitis and infections.",
       ["Long curly coat that fails to shed (hirsutism)", "Chronic/laminitis without dietary cause", "Abnormal fat deposits above eyes", "Excessive drinking/urination", "Chronic infections/slow healing", "Muscle wasting along topline", "Lethargy"],
       ["Age-related degeneration of pituitary neurons", "Not caused by management — hormonal disease"],
       "Baseline ACTH test (season-adjusted values) + TRH stimulation if borderline. Clinical hirsutism alone is strongly suggestive in seniors.",
       "Pergolide mesylate daily (lifelong, dose titrated to response). Manage as laminitis-risk: low-sugar diet, restricted grass, regular farriery. Dental/skin vigilance.",
       "No true prevention (age-related), but annual senior screening catches it before laminitis strikes. Test any horse 15+ showing coat changes.",
       ["Ponies", "Morgan", "Quarter Horse", "All breeds over age 15"],
       "If your senior horse grows a curly winter coat in summer or gets foot sore without diet change, ask your vet about an ACTH test. Treatment is cheap and transformative.",
       "Acute laminitis onset in a PPID horse = treat both aggressively; this combination is the leading cause of euthanasia in aged horses.",
       [M, "Equine Endocrinology Group PPID recommendations"]),
]

CATTLE_CONDITIONS = [
    _c("cattle", "Mastitis", "mastitis-cattle", "mammary", "urgent",
       "Udder infection — the costliest dairy disease globally. Ranges from mild (flaky milk) to gangrenous. Spreads cow-to-cow through milking hygiene failures. Affects milk quality and food safety.",
       ["Hot/swollen/painful quarter", "Clots/flakes/watery milk", "Fever and depression (severe)", "Hard cold udder with discolored secretion (gangrenous)", "Reduced milk yield"],
       ["Bacteria entering through teat canal (Staph, Strep, E.coli)", "Dirty bedding/milking equipment", "Teat-end damage", "Flies", "Wet muddy lots"],
       "California Mastitis Test (CMT) on-farm, somatic cell counts, milk culture identifies organism for treatment choice.",
       "Intramammary antibiotics after culture when possible, frequent milk-out (never stop milking an infected quarter), NSAIDs for inflammation. Severe systemic cases need IV therapy. Gangrenous = surgical/vet emergency.",
       "Post-milking teat dipping, clean dry bedding (sand best), properly functioning milking equipment, dry-cow therapy, fly control, cull chronic carriers.",
       ["High-producing dairy cows", "Cows with damaged teat ends"],
       "Milk the affected quarter out completely and frequently (every few hours), dip teat, isolate from the milking line, record which quarter. Culture before blanket antibiotic use.",
       "Cow off feed, fever >103.5F, cold hard udder, or blood-tinged secretions = immediate vet. Gangrene progresses hourly.",
       [M, "National Mastitis Council guidelines"]),
    _c("cattle", "Calf Scours", "scours-calves", "gastrointestinal", "emergency",
       "Diarrhea in neonatal calves — the leading killer of pre-weaned calves. Multiple infectious causes; dehydration kills faster than the infection itself. A whole-herd signal when multiple calves scour.",
       ["Watery feces (white/yellow/bloody depending on cause)", "Sunken eyes", "Weakness/reluctance to nurse", "Cold extremities (shock stage)", "Skin tenting (dehydration)"],
       ["Rotavirus/coronavirus", "Cryptosporidium (zoonotic!)", "E.coli K99 (first week)", "Salmonella (zoonotic)", "Coccidia (older calves)", "Poor colostrum intake underlying most cases"],
       "Age of calf + fecal character suggest cause; fecal antigen tests confirm. Dehydration percent assessed clinically.",
       "ORAL ELECTROLYTES are the core treatment — give at first soft stool, before the calf stops nursing. IV fluids for down/recumbent calves. Specific antimicrobials depend on pathogen. Warmth matters as much as fluids.",
       "COLOSTRUM within 4 hours of birth is the single biggest factor (10% bodyweight). Clean calving areas, all-in/all-out pen management, vaccinate dams against common scours pathogens pre-calving.",
       ["Calves 1-30 days old", "Calves with failed colostrum transfer", "Crowded/calving-season pens"],
       "Start oral electrolytes NOW (available at farm stores) even if still nursing. Isolate the calf. Wear gloves — crypto and salmonella infect humans. Vet if the calf won't stand/nurse or is <5 days old.",
       "Down calf, inability to stand, cold mouth/extremities, or no suckle reflex = IV fluids needed immediately. These calves die of dehydration, not diarrhea.",
       [M, "Merck calf health resources", "Zoetis scours prevention guides"]),
    _c("cattle", "Foot Rot (Interdigital Necrobacillosis)", "foot-rot-cattle", "orthopedic", "urgent",
       "Bacterial infection between the toes causing sudden severe lameness. Contagious through wet/muddy environments. Responds well to early treatment; neglected cases involve joint and tendon.",
       ["Sudden lameness (often rear)", "Symmetric swelling above BOTH claws", "Foul smell in the interdigital space", "Split between toes with dead tissue", "Fever in acute cases"],
       ["Fusobacterium necrophorum entering broken skin", "Wet muddy lots", "Rough stony surfaces damaging skin", "Foot traffic through filth"],
       "Clinical exam: the classic symmetric swelling + foul interdigital fissure. Rule out abscess/sole ulcer.",
       "Systemic antibiotics (oxytetracycline or tulathromycin), clean/dry the foot, topical interdigital treatment. Severe cases need hoof trimming under block. Vaccination available (Fusoguard) in endemic operations.",
       "Keep lots dry and scraped, footbaths (zinc sulfate) in dairies, smooth walking surfaces, vaccination in problem herds.",
       ["Cattle on wet lots", "Dairy cattle", "Feedlot cattle"],
       "Catch and restrain safely, examine between the claws, keep the animal on dry footing, call vet for antibiotics — early treatment resolves in days vs weeks.",
       "Swelling extending up the leg, joint involvement, or animal unable to bear weight = deeper infection needing aggressive care.",
       [M, "Iowa State extension beef resources"]),
    _c("cattle", "BVD (Bovine Viral Diarrhea)", "bvd", "infectious", "urgent",
       "Viral disease with devastating reproductive consequences. Persistently Infected (PI) animals shed virus for life and quietly infect herdmates. Herd-level biosecurity disease — testing for PIs is fundamental.",
       ["Adults: fever, diarrhea, nasal discharge, ulcers in mouth", "Calves born weak/small or with tremors", "Infertility/embryo loss", "Severe mucosal disease (PI animals): fatal bloody diarrhea", "Immunosuppression opening door to pneumonia/scours"],
       ["Persistently Infected (PI) carrier animals", "Fetal infection creating new PIs", "Fenceline contact, shared water, transport commingling"],
       "Ear-notch PI test (all calves + replacements), serology for exposure, PCR pooling strategies for herd screening.",
       "No treatment for the virus itself — supportive care for secondary infections. THE answer is identification/removal of PI animals and biosecurity. Vaccinate clean herds.",
       "Test all purchased additions BEFORE arrival (ear notch). Maintain closed herd where possible. Vaccinate per veterinarian's schedule. Never co-mingle untested stock.",
       ["Herds purchasing cattle without testing", "Commingled stocker/feedlot cattle"],
       "If you see unexplained diarrhea + respiratory signs across ages, or a poor-doing calf among healthy peers, ask your vet about PI testing — it's cheap and definitive.",
       "Mucosal disease presentation (bloody diarrhea, oral ulcers, rapid decline) in a young animal = usually a PI animal dying; expect more cases until the source is found.",
       [M, "APHIS BVD control guidance"]),
    _c("cattle", "Hardware Disease (Traumatic Reticulitis)", "hardware-disease", "gastrointestinal", "emergency",
       "Swallowed metal (wire, nails) settles in the reticulum, punctures through its wall causing infection and sometimes pericarditis (heart sac infection). Preventable with magnets — expensive to treat once advanced.",
       ["Reluctant to move/grunt on pressure behind the elbow", "Arched back, elbows held out", "Off feed, slow rumen", "Fever", "Prefers standing, won't lie down", "With heart involvement: chest edema, jugular pulse"],
       ["Swallowed wire/nails in feed or pasture", "Baled twine/wire contamination", "Old building sites grazed"],
       "History + clinical signs; withers pinch test; ultrasound/radiographs; pericarditis confirmed by fluid analysis.",
       "Oral magnet (retains metal harmlessly) + antibiotics + rumen magnet for early cases. Advanced pericarditis has poor prognosis; rumenotomy surgery sometimes attempted.",
       "Feed magnets for all adult cattle — cheap insurance. Magnet bolus at first handling. Keep baling wire out of fields. Screen feed sources.",
       ["Adult dairy cows (highest feed exposure)", "Any cattle on old/homestead ground"],
       "Call vet promptly if you suspect hardware — a $20 magnet placed early prevents a dead cow. Do not force exercise.",
       "Chest edema, loud pericardial splash, or collapse = advanced pericarditis; prognosis grave. Earlier detection next time — this is why magnets exist.",
       [M, "Cornell large animal resources"]),
    _c("cattle", "Grass Tetany (Hypomagnesemia)", "grass-tetany", "metabolic", "emergency",
       "Magnesium deficiency typically in lactating cows on lush spring grass. Fast-moving: normal cow in morning can be dead by evening. Prevention via mineral program is everything.",
       ["Excitability/skittish behavior", "Muscle twitching/staggering", "Hyper-sensitivity to sound/touch", "Collapse with paddling seizures", "Death without intervention"],
       ["Lush fast-growing spring pasture (low Mg uptake)", "Lactation drain (milk carries Mg)", "High potassium fertilization blocking Mg absorption", "Older cows (4th+ lactation) highest risk"],
       "Clinical signs + season/lactation status; blood magnesium (samples often post-mortem); response to treatment confirms.",
       "IV calcium-magnesium solution SLOWLY (calm handling — stress kills these cows). Oral Mg oxide for less acute cases. Recovered cows need continued supplementation.",
       "High-Mg mineral offered free-choice 30 days before spring turnout and through lush growth. Limit K-heavy fertilizer on pasture. Legume mix dilutes risk vs pure ryegrass.",
       ["Older lactating cows", "Beef herds on spring wheat/ryegrass pasture", "British breeds slightly higher risk"],
       "If you find a twitchy staggering fresh cow on spring grass: handle QUIETLY, call vet for IV Mg-Ca immediately. Stress during handling triggers seizures.",
       "Convulsions, recumbency, or coma = minutes matter. Have the vet come rather than transporting if at all possible.",
       [M, "State extension grass tetany bulletins"]),
]

GOAT_CONDITIONS = [
    _c("goat", "Coccidiosis", "coccidiosis-goat", "parasitic", "urgent",
       "Intestinal protozoal infection of kids — the classic 'poor-doing kid' disease. Damages gut lining causing diarrhea and permanent growth setback. Management-related: crowding and dirty water drive outbreaks.",
       ["Diarrhea (sometimes bloody) in kids 3wk-5mo", "Poor growth despite appetite", "Rough hair coat", "Straining to defecate", "Dehydration", "Occasionally sudden death in heavy infections"],
       ["Overcrowding", "Contaminated water/feed with feces", "Wet dirty pens", "Stress (weaning, transport) activating latent infection"],
       "Fecal flotation counts oocysts (context matters — adults carry some normally). Clinical picture in a kid is usually sufficient.",
       "Sulfa drugs or amprolium (off-label, vet-directed), fluids for dehydrated kids, coccidiostats in feed/water for herd outbreaks. Recovery of gut function takes weeks.",
       "Clean dry pens, elevated feeders/waterers kids can't contaminate, avoid overcrowding, coccidiostat inclusion at weaning in problem herds, lime pen floors between groups.",
       ["Kids 3 weeks to 5 months", "Intensively-raised kids", "Weaning-age groups"],
       "Isolate scouring kids, fluids/electrolytes, get a fecal. Treat the GROUP, not just obvious cases — clinical kid means pen-mates are loaded.",
       "Bloody diarrhea with weakness/dehydration in a young kid = same-day vet; heavy coccidia loads kill quickly.",
       [M, "ACSRPC coccidia resources"]),
    _c("goat", "CAE (Caprine Arthritis Encephalitis)", "cae-caprine-arthritis", "infectious", "chronic",
       "Retrovirus spread primarily through infected milk/colostrum. Two forms: chronic arthritis in adults, progressive paralysis in kids 2-6 months. No cure — control is prevention of transmission.",
       ["Adults: swollen painful joints (especially knees), progressive weight loss, firm udder with reduced milk", "Kids: ascending paralysis, weakness in rear then front limbs", "Chronic pneumonia signs"],
       ["Infected colostrum/milk feeding", "Close prolonged contact (rare)", "Birth fluids"],
       "Serology (ELISA) — note kids carry maternal antibodies until ~6mo so test after that age. PCR available.",
       "No treatment. Supportive care for arthritic adults. Kids with neuro form are eventually euthanized. Control: SNAPSHOT the herd, separate kids at birth, feed heat-treated colostrum/pasteurized milk.",
       "CAE-negative herd maintenance: test annually, bottle-feed kids pasteurized milk from negative does, single-use needles, don't pool raw milk for feeding.",
       ["Dairy breeds historically highest prevalence (Alpine, Saanen)", "Any herd feeding raw pooled milk"],
       "If buying goats, demand recent CAE-negative papers. If your herd has positive animals, talk to your vet about a prevention plan before the next kidding season.",
       "A paralyzed kid is a welfare decision point — humane euthanasia after confirmation. Adults rarely need emergency care; they need management planning.",
       [M, "Washington State University CAE research"]),
    _c("goat", "Foot Rot / Hoof Abscess Complex", "hoof-rot-footrot-goat", "orthopedic", "urgent",
       "Hoof infections from wet environments and neglected trims. Foot rot is contagious between goats; abscesses are individual. Both cause real production loss — lame goats don't eat properly.",
       ["Limping/holding a foot up", "Heat in the hoof", "Foul smell (foot rot)", "Under-run sole or black discharge", "Reluctance to move to feed"],
       ["Wet muddy pens", "Missed trim schedule", "Contagious bacteria (Dichelobacter) introduced by new stock", "Concrete abrasion"],
       "Hoof examination — lift and smell (foul = rot). Trim reveals under-running sole or abscess tract.",
       "Trim ALL affected tissue (bleeding is expected — trim to healthy horn), topical treatment, dry environment, systemic antibiotics for severe rot. Individual abscesses resolve after draining trim.",
       "Trim every 8 weeks minimum (more often in wet seasons). Quarantine/trim incoming animals. Keep pens dry. Cull chronically lame lines — resistance varies genetically.",
       ["Goats in wet climates", "Overdue trim schedules", "Herd introductions without quarantine"],
       "Catch the goat, trim the foot clean yourself if experienced, apply topical treatment, move to dry footing. Whole herd may need checking — where there's one, there's usually more.",
       "Lame goat unable to reach food/water, or rot involving the upper foot/joint = vet intervention for systemic antibiotics.",
       [M, "Langston University goat research extension"]),
    _c("goat", "Urinary Calculi (Water Belly)", "urinary-calculi-goat", "urinary", "emergency",
       "Stones blocking the urethra of male goats — especially wethers fed grain. The urethra is narrow and has a small diverticulum that traps stones. A blocked wether ruptures its bladder and dies. Diet-driven and preventable.",
       ["Straining to urinate with little/no urine", "Crystal grit on preputial hairs", "Restlessness/kicking at belly", "Tail twitching", "Grinding teeth", "Bloody urine", "Rupture: belly fills with fluid, apparent relief then depression"],
       ["High-grain/low-calcium diets", "Improper calciumhosphorus ratio (target 2:1)", "Insufficient water intake", "Early castration narrowing urethral development"],
       "Clinical signs in a male goat on grain = presumptive. Ultrasound/urinalysis confirm. Bloodwork shows kidney damage level.",
       "VET EMERGENCY: ammonium chloride drench may dissolve small stones; urinary catheterization or surgery (perineal urethrostomy) for obstruction. Pain management critical. Prognosis guarded once ruptured.",
       "Ammonium chloride in the ration (prevents stone formation), proper Ca:P ratio ≥2:1, limit grain to growing/working animals, ALWAYS fresh water (add salt lightly to encourage drinking), delay castration to 8+ weeks when possible.",
       ["Wethered males (pet goats!) on grain diets", "Show/goat-pet wethers overfed for condition", "Any male on high-grain feed"],
       "If your wether strains or you see grit around his pizzle: remove ALL grain today, ensure water access, add ammonium chloride, and call the vet if he produces no urine in several hours of straining.",
       "No urine produced + straining + grinding teeth = blocked. Hours matter — bladder rupture or kidney failure follows. This is the #1 preventable death of pet wethers.",
       [M, "Langston University urinary calculi resources"]),
    _c("goat", "Ketosis (Lactation Energy Crash)", "ketosis-lactation", "metabolic", "urgent",
       "Energy deficit in high-producing dairy does in early lactation — she can't eat enough to fuel milk production and starts breaking down fat, poisoning herself with ketones. Related to pregnancy toxemia (same mechanism, different timing).",
       ["Drop in milk production", "Off feed (starts refusing grain)", "Sweet acetone breath", "Weight loss", "Depression/lethargy", "Sometimes nervous signs"],
       ["Peak lactation energy demand exceeding intake", "Body condition too thin OR too fat going into kidding", "Multiple kids nursing", "Parasite load competing for nutrients"],
       "Blood ketone meter (works like human ketone meters), urine strips, history of early lactation + high production.",
       "Oral propylene glycol 2x daily, IV dextrose for severe cases, B vitamins (appetite stimulant), address primary issues (worms, mastitis). Reduce kids' milk demand temporarily if needed.",
       "Feed peak-lactation does as individuals — top-dress energy for heavy producers, keep excellent hay before them free-choice, parasite control so gut absorbs nutrition.",
       ["High-producing dairy does (Nigerian Dwarf, Alpine, Saanen)", "Does nursing triplets+", "Thin freshened does"],
       "Start propylene glycol immediately (feed store item), offer the best hay, check for mastitis/parasites driving the deficit. Call vet if she won't drench or keeps declining.",
       "Down doe, blindness, or total feed refusal = IV dextrose territory — same-day vet. Ketosis spirals to death faster than owners expect.",
       [M, "Extension dairy goat management guides"]),
    _c("goat", "Clostridium Enterotoxemia (Overeating Disease)", "clostridium-enterotoxemia-goat", "toxic", "emergency",
       "Clostridium perfringens toxins (types C & D mainly) released when gut contents change suddenly — usually grain overload or lush pasture. Kills healthy-looking animals within hours. The 'overeating disease' that strikes the best-doing kid in the pen.",
       ["Sudden death (often the first sign)", "Severe watery/bloody diarrhea", "Abdominal pain/kicking at belly", "Neurologic signs type D: circling, head pressing, convulsions", "Depression and rapid deterioration"],
       ["Sudden ration change", "Grain binge (broke into feed room)", "Lush pasture introduction", "Slowdown of gut motility allowing toxin buildup"],
       "Often diagnosed post-mortem (history + lesions). Live suspicion based on sudden illness after diet change; toxin testing on intestinal content.",
       "Antitoxin (types C&D) if caught early, oral antibiotics to suppress clostridial growth, fluids, activated charcoal. Vaccinated animals have dramatically better outcomes. Survivors of type D may have residual neurologic damage.",
       "CDT vaccination (Clostridium C&D + tetanus) is CORE for all goats — 2-shot series then annual boosters. Boost before ration changes/transport. Gradual feed transitions ALWAYS. Feed-room security so animals can't gorge.",
       ["Fast-growing kids on creep feed", "Show goats on high-grain rations", "Recently transported/relocated animals", "Unvaccinated herds"],
       "If a goat dies suddenly and others share its diet, vaccinate the rest NOW and pull grain. Any survivor needs antitoxin fast — this moves in hours.",
       "Neurologic signs (head pressing, circling) or sudden severe diarrhea in an unvaccinated goat after a feed change = emergency tonight, not tomorrow.",
       [M, "American Goat Federation health resources"]),
]

CONDITIONS = HORSE_CONDITIONS + CATTLE_CONDITIONS + GOAT_CONDITIONS
