"""Horse, cattle, and goat breed reference data."""

def _b(name, size, wmin, wmax, life, coat, shed, groom, energy, train,
       kids, health, ex, care, diet, origin, temp):
    return {
        "name": name, "size_category": size, "weight_range_min": wmin, "weight_range_max": wmax,
        "lifespan_years": life, "coat_type": coat, "shedding_level": shed, "grooming_freq": groom,
        "energy_level": energy, "trainability": train, "good_with_kids": kids,
        "common_health_issues": health, "exercise_needs_min": ex, "care_notes": care,
        "diet_sensitivities": diet, "origin": origin, "temperament": temp,
    }

HORSE_BREEDS = [
    _b("Thoroughbred", "large", 450, 550, "25-30", "Short, fine", "low", "Daily grooming", "very high", "moderate",
       "Best for experienced handlers", "Generally good", "Colic, laminitis, bleeding (EIPH), ulcers, joint issues",
       "1-2h daily plus turnout; needs real work", "High-energy feed; ulcer-prone — forage first, small frequent meals",
       "England", "Hot-blooded, athletic, sensitive, brave"),
    _b("Quarter Horse", "medium", 430, 545, "25-30", "Short, dense", "low", "Weekly grooming", "high", "easy",
       "Excellent — calm and steady", "Excellent", "HYPP (Impressive lines), PSSM, laminitis, joint disease",
       "1h daily + turnout", "Easy keeper — watch obesity and laminitis on grass",
       "United States", "Calm, level-headed, versatile, cow-sense"),
    _b("Arabian", "medium", 380, 450, "25-35", "Short, silky", "low", "Daily grooming", "very high", "easy",
       "Good with socialization", "Good", "SCID genetic disease, equine asthma, sensitive digestion",
       "90m daily + turnout", "Sensitive; some link to high-grain colic risk. Forage-first.",
       "Arabian Peninsula", "Hot-blooded, intelligent, loyal, spirited"),
    _b("Morgan", "medium", 400, 500, "25-30", "Medium, flowing mane/tail", "moderate", "3x weekly grooming", "high", "easy",
       "Excellent family horse", "Excellent", "PSSM, Equine Metabolic Syndrome, laminitis predisposition",
       "1h daily + turnout", "Easy keeper — restrict grass with EMS history",
       "United States", "Willing, people-oriented, versatile, sturdy"),
    _b("Appaloosa", "medium", 410, 500, "25-30", "Short, spotted coat, striped hooves", "low", "Weekly grooming", "high", "moderate",
       "Good with proper handling", "Good", "Equine recurrent uveitis (moon blindness), night blindness (CSNB)",
       "1h daily + turnout", "Watch eye health; UV masks help uveitis-prone horses",
       "United States (Nez Perce)", "Independent, hardy, versatile"),
    _b("Paint Horse", "medium", 420, 545, "25-30", "Short, tobiano/overo patterns", "low", "Weekly grooming", "high", "easy",
       "Excellent", "Excellent", "Overo Lethal White Syndrome (genetic), HYPP in some lines",
       "1h daily + turnout", "General horse care; test breeding stock for LWFS",
       "United States", "Steady, friendly, athletic"),
    _b("Clydesdale", "giant", 700, 1000, "20-25", "Long feathered legs, heavy", "moderate", "Daily leg washing/feather care", "moderate", "easy",
       "Gentle giant — good when trained", "Good", "Chronic progressive lymphedema, skin scald under feathers, PSSM",
       "1-2h daily + turnout", "Feathered legs need daily inspection for mites/scald",
       "Scotland", "Gentle, patient, striking movement"),
    _b("Percheron", "giant", 820, 1200, "25-30", "Short, black or grey", "moderate", "Regular grooming", "moderate", "easy",
       "Excellent — willing and kind", "Good", "PSSM, joint stress from size, azoturia",
       "1h daily + turnout", "Draft feeding: forage-based, avoid excess grain",
       "France", "Gentle, proud, willing, strong"),
    _b("Belgian Draft", "giant", 700, 1100, "18-22", "Heavy, sorrel with flaxen mane", "moderate", "Regular grooming", "moderate", "easy",
       "Very gentle", "Good", "Junctional epidermolysis bullosa (JEB genetic), PSSM, lymphedema",
       "1h daily + turnout", "Forage-first; easy keeper tendencies",
       "Belgium", "Docile, kind, powerful work ethic"),
    _b("Shire", "giant", 850, 1220, "25-30", "Heaviest coat, profuse leg feathering", "moderate", "Daily feather care", "moderate", "easy",
       "Exceptionally calm — 'gentle giant'", "Good", "Chronic progressive lymphedema, PSSM, foot problems",
       "1-2h daily + turnout", "Largest breed — significant feed/hay costs. Feather care critical.",
       "England", "Calm, gentle, impressive"),
    _b("Friesian", "large", 544, 635, "16-18 (shorter lifespan)", "Long, black, thick feathering", "moderate", "Daily full grooming", "high", "easy",
       "Good — flashy but kind", "Good", "SHORT LIFESPAN, dwarfism gene, aortic rupture, hypersensitivity to insect bites",
       "1h daily + turnout", "Insect bite hypersensitivity common — fly control essential. Black coat sun care.",
       "Netherlands", "Elegant, willing, gentle, showy"),
    _b("Andalusian", "medium", 408, 512, "25", "Long, thick, usually grey", "moderate", "Daily grooming", "high", "easy",
       "Excellent with families", "Good", "Metabolic syndrome, melanomas (greys), small airway disease",
       "1h daily + turnout", "Prone to metabolic issues — low-starch diet advised",
       "Spain", "Noble, intelligent, sensitive, collected"),
    _b("Lipizzaner", "medium", 450, 550, "25-30", "Long; born dark, turns white", "moderate", "Daily grooming", "high", "easy",
       "Good with experienced handlers", "Good", "Melanomas (grey), digestive sensitivity",
       "1h daily + turnout", "Slow maturing — don't start young. Long-lived breed.",
       "Austria / Slovenia", "Intelligent, dignified, athletic"),
    _b("Standardbred", "medium", 400, 520, "25-30", "Short, any solid color", "low", "Weekly grooming", "high", "easy",
       "Excellent — famous as harness racers turned family horses", "Excellent", "Post-racing lameness, ulcers in retirees",
       "1h daily + turnout", "Retired racers transition beautifully to riding homes",
       "North America", "Even-tempered, durable, honest"),
    _b("Tennessee Walking Horse", "medium", 408, 544, "25-30", "Short, glossy", "low", "Weekly grooming", "moderate", "easy",
       "Excellent — smooth gait suits older riders", "Good", "Laminitis, obesity (easy keeper)",
       "45-60min daily + turnout", "Easy keeper — manage weight carefully",
       "Tennessee, USA", "Gentle, calm, smooth-running walk"),
    _b("Mustang", "medium", 320, 420, "25-30", "Short, extremely hardy", "low", "Minimal needed", "high", "challenging",
       "Not typical — needs training/syndication programs", "Good", "Extremely sound; few breed-specific diseases",
       "Daily turnout essential; thrives on space", "Evolved on sparse forage — very easy keeper, laminitis risk on rich grass",
       "North American wild", "Hardy, intelligent, strong bonds once earned"),
    _b("Haflinger", "small", 350, 400, "25-30", "Flaxen mane, chestnut body", "moderate", "2-3x weekly grooming", "high", "easy",
       "Excellent family pony-horse", "Excellent", "Equine Metabolic Syndrome, laminitis (easy keeper!)",
       "1h daily + turnout", "STRICT diet — laminitis risk on grass. Grazing muzzle often needed.",
       "Austria / Italy (Tyrol)", "Cheerful, willing, sturdy, personable"),
    _b("Icelandic Horse", "small", 330, 380, "25-30", "Dense double winter coat", "high seasonal", "Weekly; extra in spring blow-out", "moderate", "easy",
       "Excellent", "Good", "Summer eczema (insect allergy), PSSM in some lines",
       "Daily turnout mandatory", "Never feed extra — evolved on sparse forage. Tölt gait natural.",
       "Iceland", "Friendly, five-gaited, sure-footed, calm"),
    _b("Gypsy Vanner", "medium", 400, 550, "20-25", "Profuse feathering, long mane/tail", "moderate", "Daily feather/maintenance grooming", "moderate", "easy",
       "Excellent — bred for family caravan life", "Excellent", "Chronic progressive lymphedema, feather mites, PSSM",
       "1h daily + turnout", "Feather maintenance daily; easy keeper watch",
       "Ireland / UK", "Gentle, patient, eye-catching"),
    _b("Hanoverian", "large", 500, 600, "25-28", "Short, solid colors", "low", "Regular grooming", "high", "easy",
       "Sport horse — professional homes typically", "Good", "Osteochondritis dissecans (OCD), joint disease from sport work",
       "1-2h daily structured work + turnout", "Sport-horse nutrition: balanced minerals for growth",
       "Germany", "Rideable, ambitious, elastic movement"),
    _b("Oldenburg", "large", 500, 620, "25-28", "Short, dark solid colors", "low", "Regular grooming", "high", "easy",
       "Sport horse — professional/amateur competition homes", "Good", "OCD, suspensory injuries from jumping careers",
       "1-2h daily structured work + turnout", "Performance-horse feeding program",
       "Germany", "Bold, generous, world-class sport horse"),
    _b("Miniature Horse", "small", 70, 115, "25-35", "Double coat, all colors", "moderate", "Weekly grooming", "moderate", "easy",
       "Excellent pet when handled properly", "Good", "MAJOR laminitis/EMS risk, dental crowding, obesity is deadly",
       "Turnout daily; light exercise", "CRITICAL: restricted diet, no rich grass, measured hay. Obesity = founder death risk.",
       "Europe / United States", "Curious, friendly, deceptively strong"),
]

CATTLE_BREEDS = [
    _b("Holstein", "giant", 580, 730, "4-6 (commercial); up to 15 possible", "Black-and-white patched short coat", "low", "Minimal; hoof trimming 2x/year", "moderate", "moderate",
       "Generally docile but large — caution around children", "Caution — prey animal", "Mastitis, lameness, ketosis, milk fever, displaced abomasum",
       "Pasture/free-stall; high production demands", "High-energy lactation diet; calcium management at calving",
       "Netherlands", "Calm, high-production dairy, creature of routine"),
    _b("Angus", "large", 500, 900, "15-20+", "Solid black (or red), polled", "low", "Minimal; seasonal shedding", "moderate", "docile",
       "Generally docile", "Caution", "Few genetic issues; eye cancer in white-faced lines, bloat on lush pasture",
       "Grass-fed systems ideal", "Efficient grazers — avoid over-fattening on grain",
       "Scotland", "Docile, polled, excellent mothers, marbling beef"),
    _b("Hereford", "large", 550, 1000, "15-20+", "Red body, white face/underline", "low", "Minimal", "moderate", "docile",
       "Known for docility", "Caution", "Eye cancer (cancer eye) from UV on pink skin, foot rot",
       "Range or pasture systems", "Hardy grazer; minimal supplementation",
       "England", "Docile, hardy, good mothers, range-adapted"),
    _b("Jersey", "medium", 360, 540, "12-15 commercial; longer possible", "Light brown/fawn, black nose", "low", "Minimal", "moderate", "docile",
       "Smaller size gentler than Holsteins", "Caution", "Milk fever (calcium), ketosis, small-calf dystocia concerns",
       "Pasture-friendly dairy", "Lower-volume, higher-butterfat milk; careful calcium at freshening",
       "Jersey Island", "Curious, gentle, efficient grazers, pretty eyes"),
    _b("Charolais", "giant", 600, 1130, "15-20+", "White/cream short coat", "low", "Minimal", "moderate", "moderate",
       "Can be flightier than Angus/Hereford", "Caution", "Dystocia in calves, heat stress darker climates",
       "Range or pasture", "Muscular — watch for stress myopathy in handling",
       "France", "Alert, muscular, terminal sire breed"),
    _b("Simmental", "large", 590, 1050, "15-20+", "Yellow/red-brown to black, white face common", "low", "Minimal", "moderate", "docile",
       "Generally calm", "Caution", "Few major issues; pulmonary hypertension in high-altitude lines",
       "Pasture or mixed systems", "Dual-purpose; good feed conversion",
       "Switzerland", "Docile, dual-purpose (dairy/beef), fast-growing calves"),
    _b("Limousin", "large", 560, 1000, "15-20+", "Golden-red to black short coat", "low", "Minimal", "moderate", "moderate",
       "More reserved than Angus", "Caution", "Calving ease varies by line; few genetic diseases",
       "Range/pasture systems", "Lean beef genetics; efficient forage converter",
       "France", "Alert, lean-muscled, maternal"),
    _b("Brahman", "large", 450, 1000, "15-20+", "Short light-grey/red with loose skin, hump", "low", "Minimal", "moderate", "moderate",
       "Protective mothers — respect cows with calves", "Caution", "Few diseases; heat-tolerant; insect resistant",
       "Hot/humid range systems ideal", "Heat-adapted; efficient on poor forage",
       "United States (from Indian Zebu)", "Intelligent, protective, heat/insect tolerant"),
    _b("Highland", "medium", 400, 800, "18-22+", "Long shaggy double coat, long horns", "low", "Seasonal brushing", "moderate", "docile",
       "Very docile — iconic pet cattle", "Caution (horn presence)", "Remarkably healthy; occasional bloat, eye issues in heavy hair",
       "Harsh-climate pasture perfect", "Thrives on poor forage other breeds can't use",
       "Scottish Highlands", "Gentle, hardy, iconic looks, cold-adapted"),
    _b("Guernsey", "medium", 400, 550, "12-15", "Fawn and white markings", "low", "Minimal", "moderate", "docile",
       "Gentle dairy disposition", "Caution", "Milk fever, mastitis, ketosis like other dairy breeds",
       "Pasture dairy", "Golden milk (beta-carotene); moderate production",
       "Guernsey Island", "Docile, curious, efficient converters"),
    _b("Brown Swiss", "large", 590, 640, "12-15+", "Solid grey-brown to silver", "low", "Minimal", "moderate", "docile",
       "Calm, sturdy dairy breed", "Caution", "Few breed-specific issues; mastitis resistance above average",
       "Alpine-origin pasture or free-stall", "Good feed conversion; strong feet/legs",
       "Switzerland", "Calm, oldest dairy breed, strong bones"),
    _b("Texas Longhorn", "large", 400, 900, "15-25+", "Any color pattern; massive spread horns", "low", "Minimal", "moderate", "moderate",
       "Respect the horns — not for close quarters", "Horn defense vs predators", "Extremely disease/parasite resistant",
       "Harsh range systems ideal", "Survives on poor forage where others starve",
       "Spain via Mexico/Texas", "Independent, hardy, iconic horns"),
]

GOAT_BREEDS = [
    _b("Boer", "large", 90, 140, "8-12 (breeding does often shorter)", "Short white body, red head", "low", "Hoof trim every 6-8 weeks", "moderate", "docile",
       "Generally gentle", "Caution", "Parasites (barber pole), bloat, pregnancy toxemia",
       "Brush clearing + pasture", "Meat goat — efficient browse/graze converter",
       "South Africa", "Docile, fast-growing, prime meat breed"),
    _b("Nubian", "medium", 61, 100, "10-15", "Short sleek coat, long pendulant ears, roman nose", "low", "Hoof trim 6-8 weeks; minimal coat care", "moderate", "docile",
       "Vocal and friendly", "Caution", "Parasites, mastitis, weak pasterns",
       "Pasture/browse + grain for milkers", "Higher butterfat milk; heat-tolerant",
       "England (from African/Near Eastern stock)", "Vocal, dramatic, affectionate, stubborn charm"),
    _b("Alpine", "medium", 61, 78, "10-15", "Short, any color/pattern", "low", "Hoof trim 6-8 weeks", "moderate", "docile",
       "Friendly herd animals", "Caution", "CAE, CL (contagious abscesses), parasites",
       "Browse + quality hay for milking", "Excellent milk volume; grain for heavy producers",
       "French Alps", "Alert, independent, excellent dairy"),
    _b("Saanen", "medium", 63, 82, "10-15", "Short pure white (sensitive to sun)", "low", "Hoof trim 6-8 weeks", "moderate", "docile",
       "Calm — best beginner dairy goat", "Caution", "Sunburn on ears/udders (white skin), CAE, parasites",
       "Browse + hay; shade access required", "Highest volume dairy breed; needs quality feed",
       "Switzerland", "Calm, productive, sensitive to sun"),
    _b("LaMancha", "medium", 57, 75, "10-15", "Short any color; tiny gopher ears", "low", "Hoof trim 6-8 weeks", "moderate", "docile",
       "Sweet temperament, great family goat", "Caution", "Fewer ear issues than expected; standard goat parasites",
       "Browse + hay for milkers", "High butterfat milk; hardy",
       "United States (Oregon)", "Gentle, quiet, distinctive ears"),
    _b("Toggenburg", "medium", 55, 70, "10-15", "Short brown/chamois with white facial stripes", "low", "Hoof trim 6-8 weeks", "moderate", "docile",
       "Gentle, sometimes shy", "Caution", "Standard goat parasites, mastitis",
       "Cool climate pasture preferred", "Consistent milkers; less heat tolerant",
       "Switzerland (Toggenburg valley)", "Gentle, alert, oldest registered breed"),
    _b("Nigerian Dwarf", "small", 16, 34, "12-18", "Short any color; mini size", "low", "Hoof trim 6-8 weeks", "moderate", "easy",
       "EXCELLENT with children — popular family goat", "Caution", "Hypocalcemia in late pregnancy, parasites, difficult births if bred to large bucks",
       "Small-space browse; measured grain", "Mini dairy — surprisingly high butterfat. Watch weight.",
       "West Africa via United States", "Playful, affectionate, manageable size"),
    _b("Pygmy", "small", 16, 27, "12-18", "Dense coat, any agouti color; stocky build", "low", "Hoof trim 6-8 weeks", "moderate", "easy",
       "Popular pets — good with supervised children", "Caution", "Obesity easily, urinary stones in wethers (castrate males), parasites",
       "Small pasture; strict diet — pets get fat", "Pet/meat heritage; do NOT overfeed grain to wethers",
       "West Africa", "Compact, playful, hardy little characters"),
    _b("Kiko", "medium", 54, 91, "8-12", "Short double coat, any color", "low", "Minimal hoof care (hardy feet)", "moderate", "moderate",
       "Less handleable — commercial meat focus", "Caution", "Very parasite-resistant compared to other goats",
       "Low-input brush/range systems designed for them", "Bred FOR parasite resistance and mothering — minimal intervention",
       "New Zealand", "Independent, vigorous, survival-selected"),
    _b("Spanish Goat", "medium", 50, 91, "8-14", "Short varied coat, many colors; often horned", "low", "Minimal hoof care", "moderate", "challenging",
       "Wild-type — not pet goats", "Caution", "Extremely hardy; minimal disease susceptibility",
       "Brush-clearing range operations", "The ultimate low-input browser",
       "Spain via early Spanish settlers", "Flighty, self-sufficient, unmatched foragers"),
]
